import {adminClient,checked,response,stripe} from '../_shared/runtime.ts';
Deno.serve(async(req:Request)=>{if(req.method!=='POST')return response({},405);const admin=adminClient();const token=(req.headers.get('Authorization')??'').replace(/^Bearer /,'');const allowed=await admin.rpc('worker_authorized',{p_token:token});if(allowed.error||allowed.data!==true)return response({error:'No autorizado'},401);try{
 const jobs=await checked(admin.rpc('claim_push_jobs'));
 for(const j of jobs){try{
 const r=await fetch('https://exp.host/--/api/v2/push/send',{method:'POST',headers:{'Content-Type':'application/json',...(Deno.env.get('EXPO_ACCESS_TOKEN')?{Authorization:'Bearer '+Deno.env.get('EXPO_ACCESS_TOKEN')}: {})},body:JSON.stringify({to:j.token,title:j.title,body:j.body,sound:'default',channelId:'appointments',data:{appointment_id:j.appointment_id}})});const body=await r.json();const ticket=Array.isArray(body.data)?body.data[0]:body.data;await checked(admin.rpc('finish_push_job',{p_id:j.id,p_ticket:r.ok&&ticket?.status==='ok'?ticket.id:null,p_error:ticket?.details?.error??null,p_dead:ticket?.details?.error==='DeviceNotRegistered'}));
 }catch{await admin.rpc('finish_push_job',{p_id:j.id,p_ticket:null,p_error:'Network delivery uncertain',p_dead:false})}}
 const receipts=await checked(admin.rpc('push_receipts'));if(receipts.length){const r=await fetch('https://exp.host/--/api/v2/push/getReceipts',{method:'POST',headers:{'Content-Type':'application/json',...(Deno.env.get('EXPO_ACCESS_TOKEN')?{Authorization:'Bearer '+Deno.env.get('EXPO_ACCESS_TOKEN')}: {})},body:JSON.stringify({ids:receipts.map((x:{ticket_id:string})=>x.ticket_id)})});if(r.ok){const result=await r.json();for(const row of receipts){const receipt=result.data?.[row.ticket_id];if(receipt)await checked(admin.rpc('finish_push_receipt',{p_id:row.id,p_error:receipt.status==='ok'?null:receipt.details?.error??'Provider rejected'}))}}}
 // Refund idempotency prevents duplicate reimbursements if a worker retries.
 if(Deno.env.get('STRIPE_SECRET_KEY')){const refunds=await checked(admin.from('payments').select('*').in('state',['refund_pending','refund_failed']).limit(30));for(const p of refunds??[]){try{const refund=p.refund_id?await stripe('refunds/'+encodeURIComponent(p.refund_id)):await stripe('refunds',{payment_intent:p.payment_intent,reverse_transfer:'true'},'refund-'+p.appointment_id);const state=refund.status==='succeeded'?'refunded':refund.status==='failed'||refund.status==='canceled'?'refund_failed':'refund_pending';await checked(admin.from('payments').update({state,refund_id:refund.id}).eq('appointment_id',p.appointment_id));if(state==='refunded')await checked(admin.from('appointments').update({outcome:'refunded'}).eq('id',p.appointment_id));}catch{await admin.from('payments').update({state:'refund_failed'}).eq('appointment_id',p.appointment_id)}}}
 const files=await checked(admin.rpc('cleanup_files'));for(const f of files){await checked(admin.storage.from(f.bucket).remove([f.path]));await checked(admin.rpc('cleaned_file',{p_id:f.id}))}
 return response({processed:jobs.length});
}catch{return response({error:'Worker pendiente de reintento'},500)}});
