import * as ImagePicker from 'expo-image-picker';
import {ImageManipulator,SaveFormat} from 'expo-image-manipulator';
import * as Crypto from 'expo-crypto';
import {decode} from 'base64-arraybuffer';
import {db} from './supabase';
export async function uploadPhoto(user:string,shop:string,kind:string,caption:string,target?:string){const picked=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:1,exif:false});if(picked.canceled)return;const context=ImageManipulator.manipulate(picked.assets[0].uri);context.resize({width:1200});const rendered=await context.renderAsync();const img=await rendered.saveAsync({format:SaveFormat.JPEG,compress:.82,base64:true});if(!img.base64)throw Error('No pudimos preparar la foto.');const file=decode(img.base64);if(file.byteLength>5242880)throw Error('La imagen es demasiado grande.');const path=`${user}/${shop}/${Crypto.randomUUID()}.jpg`;const {error}=await db().storage.from('portfolio').upload(path,file,{contentType:'image/jpeg',upsert:false});if(error)throw error;const {error:rowError}=await db().from('photos').insert({shop_id:shop,kind,caption,storage_path:path,barber_id:kind==='barber'?target:null,service_id:kind==='cut'?target:null});if(rowError){await db().storage.from('portfolio').remove([path]);throw rowError}}

export async function uploadAppointmentPhoto(user:string,appointment:string,kind:'reference'|'review'){const picked=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:1,exif:false});if(picked.canceled)return;const context=ImageManipulator.manipulate(picked.assets[0].uri);context.resize({width:1200});const rendered=await context.renderAsync();const img=await rendered.saveAsync({format:SaveFormat.JPEG,compress:.82,base64:true});if(!img.base64)throw Error('No pudimos preparar la foto.');const file=decode(img.base64);if(file.byteLength>5242880)throw Error('La imagen es demasiado grande.');const path=`${user}/${appointment}/${kind}/${Crypto.randomUUID()}.jpg`;const result=await db().storage.from('appointment-media').upload(path,file,{contentType:'image/jpeg',upsert:false});if(result.error)throw result.error;return path}

export async function uploadHaircutPhoto(user:string,appointment:string,camera=false){if(camera){const permission=await ImagePicker.requestCameraPermissionsAsync();if(!permission.granted)throw Error('Permite usar la cámara en los ajustes de tu teléfono o elige una foto de tu galería.')}const picked=camera?await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:1,exif:false}):await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:1,exif:false});if(picked.canceled)return;const context=ImageManipulator.manipulate(picked.assets[0].uri);context.resize({width:Math.min(1200,picked.assets[0].width)});const rendered=await context.renderAsync();const img=await rendered.saveAsync({format:SaveFormat.JPEG,compress:.8,base64:true});if(!img.base64)throw Error('No pudimos preparar la foto.');const bytes=decode(img.base64);if(bytes.byteLength>5242880)throw Error('Elige una foto más pequeña.');const path=`${user}/${appointment}/${Crypto.randomUUID()}.jpg`;const r=await db().storage.from('haircut-records').upload(path,bytes,{contentType:'image/jpeg',upsert:false});if(r.error)throw r.error;return path}
