import {nextDay} from './booking-helpers';
export type WeekRow={id:string;day:string;starts_at:string;customer_id:string;customer_name:string;barber_id:string;barber_name:string;status:string;total_cents:number;deposit_cents:number;discount_cents:number;minutes:number;lines:{id?:string;name:string;price_cents:number;minutes:number}[];payment_mode:string;payment_state:string|null;provider_live:boolean;paid_cents:number;returning:boolean};
export type WeekReport={shop:string;timezone:string;start:string;end:string;generated_at:string;rows:WeekRow[]};
export function summarizeWeek(report:WeekReport){
 const rows=report.rows,done=rows.filter(r=>r.status==='completed');
 const live=(r:WeekRow)=>r.provider_live&&['paid','refund_pending','refund_failed','refunded'].includes(r.payment_state??'');
 const sum=(xs:WeekRow[],field:'total_cents'|'discount_cents'|'minutes'|'paid_cents')=>xs.reduce((n,r)=>n+Number(r[field]),0);
 const customers=new Map(done.map(r=>[r.customer_id,r.returning]));
 const daily=Array.from({length:7},(_,i)=>{const day=nextDay(report.start,i),all=rows.filter(r=>r.day===day),completed=all.filter(r=>r.status==='completed');return {day,citas:all.length,completed:completed.length,value:sum(completed,'total_cents'),collected:sum(all.filter(live),'paid_cents'),refunded:sum(all.filter(r=>live(r)&&r.payment_state==='refunded'),'paid_cents')}});
 const barbers=[...new Set(rows.map(r=>r.barber_id))].map(id=>{const all=rows.filter(r=>r.barber_id===id),completed=all.filter(r=>r.status==='completed');return {id,name:all[0].barber_name,appointments:all.length,completed:completed.length,value:sum(completed,'total_cents'),minutes:sum(completed,'minutes'),cancelled:all.filter(r=>r.status==='cancelled').length,noShow:all.filter(r=>r.status==='no_show').length}}).sort((a,b)=>b.completed-a.completed);
 const serviceMap=new Map<string,{name:string;visits:number;catalog:number}>();for(const r of done)for(const l of r.lines){const key=l.id??l.name;const s=serviceMap.get(key)??{name:l.name,visits:0,catalog:0};s.visits++;s.catalog+=l.price_cents;serviceMap.set(key,s)}
 const collected=sum(rows.filter(live),'paid_cents'),refunded=sum(rows.filter(r=>live(r)&&r.payment_state==='refunded'),'paid_cents');
 return {appointments:rows.length,completed:done.length,pending:rows.filter(r=>['confirmed','arrived'].includes(r.status)).length,pendingPayment:rows.filter(r=>r.status==='pending_payment').length,cancelled:rows.filter(r=>r.status==='cancelled').length,noShow:rows.filter(r=>r.status==='no_show').length,customers:customers.size,returning:[...customers.values()].filter(Boolean).length,newCustomers:[...customers.values()].filter(v=>!v).length,value:sum(done,'total_cents'),discounts:sum(done,'discount_cents'),ticket:done.length?Math.round(sum(done,'total_cents')/done.length):0,minutes:sum(done,'minutes'),collected,refunded,net:collected-refunded,refundPending:sum(rows.filter(r=>live(r)&&['refund_pending','refund_failed'].includes(r.payment_state??'')),'paid_cents'),testValue:sum(done.filter(r=>r.payment_mode==='simulation'||(r.payment_mode==='stripe'&&!r.provider_live)),'total_cents'),daily,barbers,services:[...serviceMap.values()].sort((a,b)=>b.visits-a.visits)};
}
export const reportNotes='Citas según su fecha programada y zona horaria del negocio. Anticipos: estado actual de los pagos de esas citas, no movimientos bancarios de la semana. El valor de servicios no confirma cobro del saldo. No incluye gastos, comisiones ni ganancias netas. Clientes nuevos: sin visita completada antes del lunes; recurrentes: con visita anterior. Servicios: precios de catálogo antes de descuentos; pueden incluir extras.';
