import {unzipSync,zipSync,strFromU8,strToU8} from 'fflate';
import {decode} from 'base64-arraybuffer';
import {weeklyTemplate} from './weekly-template';
import {summarizeWeek,type WeekReport} from './weekly-stats';
type Cell=string|number|{formula:string;value:number};
const xml=(s:string)=>s.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const column=(i:number)=>String.fromCharCode(65+i);
const serial=(day:string)=>Date.parse(day+'T00:00:00Z')/86400000+25569;
const status:Record<string,string>={confirmed:'Confirmada',arrived:'Llegó',completed:'Completada',cancelled:'Cancelada',no_show:'Inasistencia',pending_payment:'Pendiente de pago'};
export function weeklyWorkbook(report:WeekReport):Uint8Array{
 const z=unzipSync(new Uint8Array(decode(weeklyTemplate))),s=summarizeWeek(report);
 const f=(formula:string,value:number)=>({formula,value});
 const metrics:Cell[][]=[['Citas totales',f('SUM(Dias!B5:B11)',s.appointments)],['Visitas completadas',f('SUM(Dias!C5:C11)',s.completed)],['Por atender',s.pending],['Pendientes de pago',s.pendingPayment],['Canceladas',s.cancelled],['Inasistencias',s.noShow],['Clientes atendidos',s.customers],['Clientes nuevos',s.newCustomers],['Clientes recurrentes',s.returning],['Valor de servicios (MXN)',f('SUM(Dias!D5:D11)',s.value/100)],['Ticket promedio (MXN)',f('IF(B6=0,0,ROUND(B14/B6,2))',s.ticket/100)],['Descuentos completados (MXN)',s.discounts/100],['Minutos completados',s.minutes],['Anticipos reales (MXN)',f('SUM(Dias!E5:E11)',s.collected/100)],['Devueltos (MXN)',f('SUM(Dias!F5:F11)',s.refunded/100)],['Después de devoluciones (MXN)',f('B18-B19',s.net/100)],['Pendientes de devolución (MXN)',s.refundPending/100],['Valor de servicios de prueba (MXN)',s.testValue/100],['Tasa de cancelación',f('IF(B5=0,0,B9/B5)',s.appointments?s.cancelled/s.appointments:0)],['Tasa de inasistencia',f('IF(B5=0,0,B10/B5)',s.appointments?s.noShow/s.appointments:0)],['Tasa de clientes recurrentes',f('IF(B11=0,0,B13/B11)',s.customers?s.returning/s.customers:0)],['Criterio de semana','Fecha programada; lunes a domingo en '+report.timezone],['Anticipos','Estado actual de los pagos de las citas de esta semana. No es un extracto de movimientos bancarios.'],['Valor de servicios','No confirma cobro del saldo. Incluye pruebas. No representa ganancias.'],['Devoluciones','El neto resta las realizadas, no las pendientes. Antes de comisiones y gastos.'],['Clientes','Nuevos: sin visitas completadas antes del lunes. Recurrentes: con al menos una visita anterior.'],['Servicios','Incluye cortes y extras de visitas completadas. Valor de catálogo antes de descuentos.'],['Fuente','Reservas y pagos de Pulso. Exportado: '+report.generated_at]];
 const rows:Cell[][][]=[metrics.slice(0,21),s.daily.map(d=>[serial(d.day),d.citas,d.completed,d.value/100,d.collected/100,d.refunded/100,d.day.slice(5)]),s.barbers.map(b=>[b.name,b.appointments,b.completed,b.value/100,b.minutes,b.cancelled,b.noShow]),s.services.map(v=>[v.name,v.visits,v.catalog/100]),report.rows.map(r=>{const date=new Date(r.starts_at);const parts=new Intl.DateTimeFormat('en-GB',{timeZone:report.timezone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date);const hour=Number(parts.find(p=>p.type==='hour')?.value??0),minute=Number(parts.find(p=>p.type==='minute')?.value??0);return [r.id,serial(r.day)+(hour*60+minute)/1440,r.customer_name,r.barber_name,status[r.status]??r.status,r.lines.map(l=>l.name).join(' + '),r.total_cents/100,r.deposit_cents/100,r.discount_cents/100,r.minutes,r.payment_mode,r.payment_state??'Sin pago',r.provider_live?'Sí':'No',r.paid_cents/100,r.returning?'Sí':'No']}),metrics.slice(21)];
 // Fill the authored template while keeping its native Excel charts and styles.
 const dateStyle=(strFromU8(z['xl/worksheets/sheet2.xml']).match(/<x:c r="A5" s="(\d+)"/)??[])[1]??'1';
 const moneyStyle=(strFromU8(z['xl/worksheets/sheet2.xml']).match(/<x:c r="D5" s="(\d+)"/)??[])[1]??'1';
 for(let i=0;i<6;i++){const path=`xl/worksheets/sheet${i+1}.xml`;let source=strFromU8(z[path]);const style=(ref:string)=>source.match(new RegExp(`<x:c r="${ref}" s="(\\d+)"`))?.[1]??'1';
 const cell=(value:Cell,col:number,row:number)=>{let st=style(column(col)+Math.min(row,39));if(row===1)st=style('A1');if(i===0&&col===1&&[14,15,16,18,19,20,21,22].includes(row))st=moneyStyle;if(i===1&&col===0)st=dateStyle;const ref=column(col)+row;if(typeof value==='number'){if(!Number.isFinite(value))throw Error('Dato numérico inválido en el reporte');return `<x:c r="${ref}" s="${st}" t="n"><x:v>${value}</x:v></x:c>`}if(typeof value==='object')return `<x:c r="${ref}" s="${st}"><x:f>${xml(value.formula)}</x:f><x:v>${value.value}</x:v></x:c>`;return `<x:c r="${ref}" s="${st}" t="inlineStr"><x:is><x:t xml:space="preserve">${xml(value)}</x:t></x:is></x:c>`};
 const heading=source.match(/<x:row r="4"[\s\S]*?<\/x:row>/)?.[0]??'';
 let body=`<x:row r="1">${cell(report.shop+' · '+['Resumen','Días','Barberos','Servicios','Citas','Lectura'][i],0,1)}</x:row><x:row r="2">${cell(`${report.start} al ${report.end} · ${report.timezone}`,0,2)}</x:row>${heading}`;
 for(let r=0;r<rows[i].length;r++)body+=`<x:row r="${r+5}" ht="${i===5?65:28}" customHeight="1">${rows[i][r].map((v,c)=>cell(v,c,r+5)).join('')}</x:row>`;
 source=source.replace(/<x:sheetData>[\s\S]*?<\/x:sheetData>/,`<x:sheetData>${body}</x:sheetData>`);z[path]=strToU8(source);
 }
 for(const [i,key] of [[1,'completed'],[2,'collected']] as const){const path=`xl/drawings/charts/chart${i}.xml`;let source=strFromU8(z[path]);source=source.replace(/<c:strCache>[\s\S]*?<\/c:strCache>/,`<c:strCache><c:ptCount val="7"/>${s.daily.map((d,j)=>`<c:pt idx="${j}"><c:v>${d.day.slice(5)}</c:v></c:pt>`).join('')}</c:strCache>`).replace(/<c:numCache>[\s\S]*?<\/c:numCache>/,`<c:numCache><c:formatCode>${i===2?'$#,##0':'0'}</c:formatCode><c:ptCount val="7"/>${s.daily.map((d,j)=>`<c:pt idx="${j}"><c:v>${key==='collected'?d.collected/100:d.completed}</c:v></c:pt>`).join('')}</c:numCache>`);z[path]=strToU8(source)}
 return zipSync(z,{level:6});
}
