import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
import {createHmac} from 'node:crypto';
const pg=new PGlite();
await pg.exec(`create role service_role bypassrls;create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,created_at timestamptz default now());create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;`);
for(const f of fs.readdirSync('supabase/migrations').filter(x=>x.endsWith('.sql')).sort())await pg.exec(fs.readFileSync('supabase/migrations/'+f,'utf8'));
const uid=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const owner=uid(1),client=uid(2),stranger=uid(3),admin=uid(4),shop=uid(5),barber=uid(6),cut=uid(7);
async function as(user,fn,role='authenticated'){await pg.query("select set_config('request.jwt.claim.sub',$1,false)",[user??'']);await pg.exec('set role '+role);try{return await fn()}finally{await pg.exec('reset role')}}
for(const [id,role] of [[owner,'owner'],[client,'client'],[stranger,'client'],[admin,'client']]){await pg.query('insert into auth.users values($1)',[id]);await as(id,()=>pg.query('insert into public.profiles(id,name,role) values($1,$2,$3)',[id,'User '+id,role]))}
await as(owner,()=>pg.query("insert into public.shops(id,owner_id,name,address,municipality,lat,lng,days,open_hour,close_hour) values($1,$2,'Pulso Test','Calle prueba','Monterrey',25.6,-100.3,'{0,1,2,3,4,5,6}',8,22)",[shop,owner]));
await as(owner,()=>pg.query("insert into public.barbers(id,shop_id,name) values($1,$2,'Barbero')",[barber,shop]));await as(owner,()=>pg.query("insert into public.services(id,shop_id,name,kind,price_cents,duration_minutes) values($1,$2,'Corte','cut',30000,30)",[cut,shop]));
const catalog=(await as(null,()=>pg.query('select public.public_catalog() as c'),'anon')).rows[0].c;assert.equal(catalog.shops.length,1);assert.equal(catalog.shops[0].owner_id,undefined);assert.equal(catalog.shops[0].verified,false);assert.equal(catalog.appointments,undefined);
await assert.rejects(as(null,()=>pg.query('select * from public.appointments'),'anon'));
await assert.rejects(as(client,()=>pg.query('select public.admin_overview()')),/administración/);
await assert.rejects(as(owner,()=>pg.query('insert into pulso_private.admin_members values($1,now())',[owner])));
await pg.query('insert into pulso_private.admin_members(user_id) values($1)',[admin]);
await assert.rejects(as(owner,()=>pg.query("select public.admin_action('verify',$1,'I verified myself')",[shop])));
await as(admin,()=>pg.query("select public.admin_action('verify',$1,'Identidad y local revisados')",[shop]));assert.equal((await as(null,()=>pg.query('select public.public_catalog() as c'),'anon')).rows[0].c.shops[0].verified,true);


await assert.rejects(as(client,()=>pg.query('select public.weekly_report($1)',[shop])),/Sin acceso/);
await assert.rejects(as(null,()=>pg.query('select public.weekly_report($1)',[shop]),'anon'));
await assert.rejects(as(owner,()=>pg.query('select public.weekly_report($1,1)',[shop])),/Semana/);
const week=(await as(owner,()=>pg.query('select public.weekly_report($1) d',[shop]))).rows[0].d;
assert.equal(week.rows.length,0);assert.ok(week.start);assert.equal(new Date(week.start+'T12:00:00Z').getUTCDay(),1);
const start=(await pg.query("select date_trunc('day',now())+interval '3 days 18 hours' s")).rows[0].s;
const args={p_barber:barber,p_service:cut,p_addons:[],p_start:start,p_expected_total:30000,p_expected_deposit:30,p_expected_cancel:12,p_accept:true,p_offer:null,p_reward:null,p_expected_discount:0};
const request=uid(800);const booking=(await as(client,()=>pg.query('select public.book_once($1,$2) id',[request,JSON.stringify(args)]))).rows[0].id;
assert.equal((await as(client,()=>pg.query('select public.book_once($1,$2) id',[request,JSON.stringify(args)]))).rows[0].id,booking);
assert.equal((await pg.query('select count(*)::int n from public.appointments')).rows[0].n,1);
assert.equal((await as(client,()=>pg.query('select public.find_booking_attempt($1) id',[request]))).rows[0].id,booking);
assert.equal((await as(stranger,()=>pg.query('select public.find_booking_attempt($1) id',[request]))).rows[0].id,null);
await assert.rejects(as(stranger,()=>pg.query('select public.book_once($1,$2)',[request,JSON.stringify(args)])),/coincide/);
await assert.rejects(as(client,()=>pg.query('select public.book_once($1,$2)',[request,JSON.stringify({...args,p_expected_total:1})])),/coincide/);
const proposed=new Date(Date.parse(start)+3600000).toISOString();
await assert.rejects(as(client,()=>pg.query('select public.reschedule_appointment($1,$2,$3)',[booking,proposed,start])),/Actualiza/);
await assert.rejects(as(client,()=>pg.query('select pulso_private.apply_accepted_reschedule($1,$2,$3)',[booking,proposed,start])));
await as(client,()=>pg.query('select public.propose_reschedule($1,$2,$3)',[booking,proposed,start]));
const change=(await as(owner,()=>pg.query('select * from public.reschedule_requests'))).rows[0];
assert.equal((await as(stranger,()=>pg.query('select * from public.reschedule_requests'))).rows.length,0);
await assert.rejects(as(client,()=>pg.query("select public.respond_reschedule($1,'accepted')",[change.id])),/permitida/);
assert.equal(Date.parse((await pg.query('select starts_at from public.appointments where id=$1',[booking])).rows[0].starts_at),Date.parse(start));
await as(owner,()=>pg.query("select public.respond_reschedule($1,'accepted')",[change.id]));
assert.equal(Date.parse((await pg.query('select starts_at from public.appointments where id=$1',[booking])).rows[0].starts_at),Date.parse(proposed));
await assert.rejects(as(owner,()=>pg.query("select public.respond_reschedule($1,'accepted')",[change.id])),/respondida/);
await assert.rejects(as(client,()=>pg.query('select public.notify_late($1,10)',[booking])),/avisar/);
await pg.query("update public.appointments set starts_at=now()+interval '20 minutes',ends_at=now()+interval '50 minutes' where id=$1",[booking]);
await assert.rejects(as(owner,()=>pg.query('select public.notify_late($1,10)',[booking])),/Sin acceso/);
await as(client,()=>pg.query('select public.notify_late($1,10)',[booking]));
await assert.rejects(as(client,()=>pg.query('select public.notify_late($1,15)',[booking])),/enviado/);
await pg.query("update public.appointments set status='completed' where id=$1",[booking]);
await pg.query("insert into public.payments(appointment_id,request_id,customer_id,shop_id,amount_cents,state,provider_live) values($1,$2,$3,$4,9000,'paid',false)",[booking,uid(801),client,shop]);
let report=(await as(owner,()=>pg.query('select public.weekly_report($1) d',[shop]))).rows[0].d;assert.equal(report.rows.length,1);assert.equal(report.rows[0].provider_live,false);assert.equal(report.rows[0].paid_cents,9000);assert.equal(report.rows[0].returning,false);
await pg.query('update public.payments set provider_live=true where appointment_id=$1',[booking]);report=(await as(owner,()=>pg.query('select public.weekly_report($1) d',[shop]))).rows[0].d;assert.equal(report.rows[0].provider_live,true);
await assert.rejects(as(owner,()=>pg.query('select public.admin_operations()')),/administración/);
assert.equal((await as(admin,()=>pg.query('select public.admin_operations() d'))).rows[0].d.ready_shops,0);
await pg.close();console.log('PASS weekly launch: owner isolation, week boundaries, idempotent booking, proposal acceptance, no direct changes, late notices, test/live payment fields, admin restrictions.');
