/* eslint-disable react-hooks/set-state-in-effect -- These effects load and synchronize server-owned records asynchronously. */
import {useEffect,useState} from 'react';
import {Alert,Image,Modal,Text,View} from 'react-native';
import {useAuth} from '../../lib/auth';
import {db,photoURL} from '../../lib/supabase';
import {uploadPhoto} from '../../lib/photos';
import {type Service,type Shop,type Photo,money} from '../../lib/types';
import {Button,Card,Choice,Copy,Failure,Field,Screen,Title,report,s} from '../../components/ui';
const initial={id:'',name:'',description:'',kind:'cut',price:'250',duration:'45',active:true};
export default function Catalog(){const {session}=useAuth();const [shop,setShop]=useState<Shop|null>(null);const [services,setServices]=useState<Service[]>([]);const [photos,setPhotos]=useState<Photo[]>([]);const [form,setForm]=useState(initial);const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function load(){if(!session)return;const {data,error}=await db().from('shops').select('*').eq('owner_id',session.user.id).maybeSingle();if(error){setError(error.message);return}setShop(data);if(!data)return;const [{data:rows,error:e},{data:images}]=await Promise.all([db().from('services').select('*').eq('shop_id',data.id).order('kind'),db().from('photos').select('*').eq('shop_id',data.id)]);if(e)setError(e.message);else{setServices(rows??[]);setPhotos(images??[]);setError('')}}useEffect(()=>{void load()},[session?.user.id]);
async function save(){if(!shop)return;const price=Math.round(Number(form.price.replace(',','.'))*100),minutes=Number(form.duration);if(!form.name.trim()||!Number.isInteger(price)||price<0||!Number.isInteger(minutes)||minutes%15!==0||minutes<0||(form.kind==='cut'&&minutes<15)){report(Error('Completa el nombre y un precio válido. La duración debe ser múltiplo de 15 minutos.'));return}setBusy(true);try{const row={shop_id:shop.id,name:form.name.trim(),description:form.description,kind:form.kind,price_cents:price,duration_minutes:minutes,active:form.active};const result=form.id?await db().from('services').update(row).eq('id',form.id).eq('shop_id',shop.id):await db().from('services').insert(row);if(result.error)throw result.error;setEditing(false);await load()}catch(e){report(e)}finally{setBusy(false)}}
return <><Screen><Title>Tu menú de servicios.</Title><Copy>Crea tus cortes y agregados. Cada uno tiene su precio y duración. Las citas ya reservadas conservan el precio original.</Copy><Failure message={error} onRetry={load}/>{shop?<><Button title="Crear corte o agregado" onPress={()=>{setForm(initial);setEditing(true)}}/>{services.map(x=>{const photo=photos.find(p=>p.service_id===x.id);return <Card key={x.id}>{photo&&<Image source={{uri:photoURL(photo.storage_path)}} style={s.photo}/>}<Text style={s.heading}>{x.name}</Text><Copy>{x.kind==='cut'?'Corte / servicio principal':'Agregado'} · {money(x.price_cents)} · {x.duration_minutes} min · {x.active?'Disponible':'Oculto'}</Copy><Button secondary title="Editar nombre, precio y duración" onPress={()=>{setForm({id:x.id,name:x.name,description:x.description,kind:x.kind,price:String(x.price_cents/100),duration:String(x.duration_minutes),active:x.active});setEditing(true)}}/><Button secondary title="Agregar foto de este servicio" disabled={busy} onPress={async()=>{setBusy(true);try{await uploadPhoto(session!.user.id,shop.id,'cut',x.name,x.id);await load()}catch(e){report(e)}finally{setBusy(false)}}}/></Card>})}</>:<Copy>Primero registra tu barbería desde Mi local.</Copy>}</Screen><Modal visible={editing} animationType="slide" onRequestClose={()=>!busy&&setEditing(false)} presentationStyle="pageSheet"><Screen><Title>{form.id?'Editar servicio':'Nuevo servicio'}</Title><Choice label="Corte o servicio principal" selected={form.kind==='cut'} onPress={()=>setForm({...form,kind:'cut'})}/><Choice label="Agregado opcional" selected={form.kind==='addon'} onPress={()=>setForm({...form,kind:'addon'})}/><Field label="Nombre, por ejemplo: Fade bajo" value={form.name} onChangeText={name=>setForm({...form,name})} maxLength={80}/><Field label="Descripción" value={form.description} onChangeText={description=>setForm({...form,description})} multiline/><Field label="Precio en pesos mexicanos" keyboardType="decimal-pad" value={form.price} onChangeText={price=>setForm({...form,price})}/><Field label="Duración en minutos (15, 30, 45…)" keyboardType="number-pad" value={form.duration} onChangeText={duration=>setForm({...form,duration})}/><Choice label="Visible para nuevas reservas" selected={form.active} onPress={()=>setForm({...form,active:!form.active})}/><Button title={busy?'Guardando…':'Guardar servicio'} disabled={busy} onPress={save}/><Button secondary title="Volver" disabled={busy} onPress={()=>setEditing(false)}/></Screen></Modal></>}
