import {useCallback,useState} from 'react';
import {Alert,Text} from 'react-native';
import {useFocusEffect} from 'expo-router';
import {useAuth} from '../../lib/auth';
import {db,rpc} from '../../lib/supabase';
import {money} from '../../lib/types';
import {Button,Card,Choice,Copy,Failure,Field,Screen,Title,report,s} from '../../components/ui';
export default function Loyalty(){const {session}=useAuth();const [shop,setShop]=useState('');const [visits,setVisits]=useState('5');const [amount,setAmount]=useState('50');const [enabled,setEnabled]=useState(false);const [locked,setLocked]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
const load=useCallback(async()=>{if(!session)return;try{const r=await db().from('shops').select('id').eq('owner_id',session.user.id).maybeSingle();if(r.error)throw r.error;if(!r.data){setError('Primero registra tu barbería en Mi local.');return}setShop(r.data.id);const [p,c]=await Promise.all([db().from('loyalty_programs').select('*').eq('shop_id',r.data.id).maybeSingle(),db().from('loyalty_stamps').select('appointment_id').eq('shop_id',r.data.id).limit(1)]);if(p.error||c.error)throw p.error||c.error;if(p.data){setVisits(String(p.data.visits_required));setAmount(String(p.data.discount_cents/100));setEnabled(p.data.enabled)}setLocked(!!c.data?.length);setError('')}catch(e){setError((e as Error).message)}},[session?.user.id]);useFocusEffect(useCallback(()=>{void load()},[load]));
async function save(){const n=Number(visits),pesos=Number(amount.replace(',','.')),cents=Math.round(pesos*100);if(!Number.isInteger(n)||n<2||n>20||!Number.isFinite(cents)||cents<100||cents>100000||Math.abs(pesos*100-cents)>.000001){report(Error('Elige de 2 a 20 visitas y un descuento de $1 a $1,000, con hasta dos decimales.'));return}setBusy(true);try{await rpc('save_loyalty',{p_shop:shop,p_visits:n,p_discount:cents,p_enabled:enabled});await load();Alert.alert('Programa guardado',enabled?'Las próximas visitas completadas acumularán recompensas.':'La acumulación está pausada. Las recompensas ganadas siguen disponibles.')}catch(e){report(e)}finally{setBusy(false)}}
return <Screen><Title>Un motivo para volver.</Title><Copy>Decide qué beneficio reciben tus clientes por regresar a tu barbería.</Copy><Failure message={error} onRetry={load}/><Field label="Visitas para ganar (2–20)" keyboardType="number-pad" value={visits} editable={!locked&&!busy} onChangeText={setVisits}/><Field label="Descuento de la recompensa (pesos)" keyboardType="decimal-pad" value={amount} editable={!locked&&!busy} onChangeText={setAmount}/><Choice label="Activar acumulación de visitas" selected={enabled} onPress={()=>!busy&&setEnabled(!enabled)}/><Card><Text style={s.heading}>Así funciona</Text><Copy>Cada {visits||'…'} visitas completadas: {Number.isFinite(Number(amount.replace(',','.')))?money(Math.round(Number(amount.replace(',','.'))*100)):'…'} de descuento en una próxima reserva de esta barbería.</Copy><Copy>Empieza al activar el programa; las visitas anteriores no suman. Cancelaciones e inasistencias no suman. Cada cita completada cuenta una vez.</Copy><Copy>El cliente elige si usa una recompensa al reservar. Se aplica al total y se recalcula el anticipo. No se acumulan dos recompensas en una cita y no se guarda saldo sobrante.</Copy><Copy>Si la cita se cancela, la recompensa vuelve a estar disponible. Si el cliente no asiste, se consume. Una pausa no borra el progreso ni los beneficios ganados.</Copy></Card>{locked&&<Copy>Ya hay visitas acumuladas. Para respetar el beneficio prometido, la meta y el descuento quedan fijos; puedes pausar o reactivar.</Copy>}<Button title={busy?'Guardando…':'Guardar programa'} disabled={busy||!shop} onPress={save}/></Screen>}
