import {useCallback,useState} from 'react';
import {useFocusEffect} from 'expo-router';
import {Text} from 'react-native';
import {useAuth} from '../../lib/auth';
import {db,rpc} from '../../lib/supabase';
import {money} from '../../lib/types';
import {Card,Copy,Failure,Screen,Title,s} from '../../components/ui';
type Stats={completed:number;cancelled:number;no_show:number;upcoming:number;simulated_total:number;returning_customers:number;top_services:{name:string;visits:number}[]};
export default function BusinessStats(){const {session}=useAuth();const [stats,setStats]=useState<Stats|null>(null);const [error,setError]=useState('');useFocusEffect(useCallback(()=>{let active=true;void(async()=>{try{const sh=await db().from('shops').select('id').eq('owner_id',session!.user.id).maybeSingle();if(sh.error)throw sh.error;if(!sh.data){if(active)setError('Registra primero tu barbería.');return}const result=await rpc<Stats>('business_stats',{p_shop:sh.data.id});if(active){setStats(result);setError('')}}catch(e){if(active)setError((e as Error).message)}})();return()=>{active=false}},[session]));return <Screen><Title>El pulso de tu negocio.</Title><Copy>Resumen de todo el historial de tu barbería.</Copy><Failure message={error}/>{stats&&<>{[['Visitas completadas',stats.completed],['Citas por atender',stats.upcoming],['Cancelaciones',stats.cancelled],['Inasistencias',stats.no_show],['Clientes que regresaron',stats.returning_customers]].map(([label,v])=><Card key={label}><Copy>{label}</Copy><Text style={s.heading}>{v}</Text></Card>)}<Card><Copy>Valor de servicios completados</Copy><Text style={s.heading}>{money(stats.simulated_total)}</Text><Copy>Importes de pruebas con pagos simulados. No representan cobros ni ganancias reales.</Copy></Card><Card><Text style={s.heading}>Servicios más solicitados</Text>{stats.top_services.length?stats.top_services.map(v=><Copy key={v.name}>{v.name} · {v.visits} visitas</Copy>):<Copy>Aparecerán después de completar visitas.</Copy>}</Card></>}</Screen>}
