import {Stack} from 'expo-router';
import {StatusBar} from 'expo-status-bar';
import {SafeAreaProvider} from 'react-native-safe-area-context';
import {ActivityIndicator,View} from 'react-native';
import {AuthProvider,useAuth} from '../lib/auth';
import ReminderSync from '../components/reminder-sync';
import {colors} from '../components/ui';
function Routes(){const {session,profile,ready}=useAuth();if(!ready)return <View style={{flex:1,backgroundColor:colors.bg,justifyContent:'center'}}><ActivityIndicator size="large" color={colors.green}/></View>;return <Stack screenOptions={{headerTintColor:colors.ink,headerStyle:{backgroundColor:colors.bg},headerShadowVisible:false,headerBackTitle:'Volver'}}><Stack.Protected guard={!profile}><Stack.Protected guard={!session}><Stack.Screen name="explore" options={{headerShown:false}}/><Stack.Screen name="guest-shop/[id]" options={{title:"Conoce la barbería"}}/></Stack.Protected><Stack.Screen name="login" options={{headerShown:false}}/></Stack.Protected><Stack.Protected guard={!!profile}><Stack.Screen name="(tabs)" options={{headerShown:false}}/><Stack.Screen name="support" options={{title:"Ayuda y reportes"}}/><Stack.Screen name="admin" options={{title:"Administración Pulso"}}/><Stack.Screen name="notifications" options={{title:"Tus avisos"}}/></Stack.Protected><Stack.Protected guard={profile?.role==='client'}><Stack.Screen name="waitlist" options={{title:'Avisos y lista de espera'}}/><Stack.Screen name="rewards" options={{title:'Mis recompensas'}}/><Stack.Screen name="shop/[id]" options={{title:'Elige tu estilo'}}/></Stack.Protected><Stack.Protected guard={profile?.role==='owner'}><Stack.Screen name="owner/client" options={{title:"Historial de cortes"}}/><Stack.Screen name="owner/offers" options={{title:'Promociones'}}/><Stack.Screen name="owner/stats" options={{title:'Tu negocio'}}/><Stack.Screen name="owner/loyalty" options={{title:'Recompensas por visitas'}}/><Stack.Screen name="owner/catalog" options={{title:'Servicios y precios'}}/><Stack.Screen name="owner/profile" options={{title:'Mi barbería'}}/><Stack.Screen name="owner/customers" options={{title:'Clientes'}}/><Stack.Screen name="owner/team" options={{title:'Mi equipo'}}/><Stack.Screen name="owner/agenda" options={{title:'Agenda'}}/></Stack.Protected><Stack.Screen name="visit/[id]" options={{title:"Barbería en Pulso"}}/><Stack.Screen name="recover" options={{title:"Recuperar cuenta"}}/><Stack.Protected guard={!!session}><Stack.Screen name="delete-account" options={{title:"Eliminar cuenta"}}/></Stack.Protected></Stack>}
export default function Root(){return <SafeAreaProvider><AuthProvider><StatusBar style="dark"/><ReminderSync/><Routes/></AuthProvider></SafeAreaProvider>}
