import {useCallback,useState} from 'react';
import {Text,View} from 'react-native';
import {router,useFocusEffect} from 'expo-router';
import {useAuth} from '../lib/auth';
import {db} from '../lib/supabase';
import {money,type Shop,type LoyaltyProgram,type LoyaltyReward} from '../lib/types';
import {Button,Card,Copy,Empty,Failure,Screen,Title,colors,s} from '../components/ui';
export default function Rewards(){const {session}=useAuth();const [programs,setPrograms]=useState<LoyaltyProgram[]>([]);const [rewards,setRewards]=useState<LoyaltyReward[]>([]);const [stamps,setStamps]=useState<{shop_id:string}[]>([]);const [shops,setShops]=useState<Shop[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
const load=useCallback(async()=>{if(!session)return;try{const results=await Promise.all([db().from('loyalty_programs').select('*'),db().from('loyalty_rewards').select('*').eq('customer_id',session.user.id).order('created_at',{ascending:false}),db().from('loyalty_stamps').select('shop_id').eq('customer_id',session.user.id),db().from('shops').select('*').eq('active',true)]);for(const r of results)if(r.error)throw r.error;setPrograms(results[0].data??[]);setRewards(results[1].data??[]);setStamps(results[2].data??[]);setShops(results[3].data??[]);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[session?.user.id]);useFocusEffect(useCallback(()=>{void load()},[load]));
const shown=programs.filter(p=>stamps.some(s=>s.shop_id===p.shop_id)||rewards.some(r=>r.shop_id===p.shop_id));
return <Screen><Title>Volver tiene recompensa.</Title><Copy>Tus visitas y beneficios, separados por barbería.</Copy><Failure message={error} onRetry={load}/>{loading?<Copy>Cargando tus recompensas…</Copy>:!shown.length&&!error&&<><Empty icon="gift-outline" title="Tu primera visita cuenta" body="Reserva en una barbería que tenga activo su programa de recompensas. Al completar la visita verás aquí tu progreso."/><Button title="Explorar barberías" onPress={()=>router.push('/')}/></>}{shown.map(p=>{const sh=shops.find(s=>s.id===p.shop_id);const count=stamps.filter(s=>s.shop_id===p.shop_id).length;const progress=count%p.visits_required;const available=rewards.filter(r=>r.shop_id===p.shop_id&&!r.used_appointment_id);return <Card key={p.shop_id}><Text style={s.heading}>{sh?.name??'Barbería no disponible'}</Text><Text style={s.pill}>{p.enabled?'SUMANDO VISITAS':'ACUMULACIÓN PAUSADA'}</Text><Copy>{progress} de {p.visits_required} visitas para tu próxima recompensa de {money(p.discount_cents)}.</Copy><View accessibilityLabel={progress+' de '+p.visits_required+' visitas'} style={{height:12,borderRadius:6,backgroundColor:colors.line,overflow:'hidden'}}><View style={{height:12,width:`${progress/p.visits_required*100}%`,backgroundColor:colors.green}}/></View><Copy>{count} visitas acumuladas en este programa.</Copy>{available.map(r=><View key={r.id} style={{backgroundColor:colors.lime,padding:16,borderRadius:16,gap:6}}><Text style={s.heading}>{money(r.discount_cents)} disponibles</Text><Copy>Úsala al reservar en esta barbería.</Copy></View>)}{!available.length&&<Copy>Aún no tienes recompensas disponibles; las que ya elegiste están vinculadas a sus citas.</Copy>}{sh&&<Button title={available.length?'Reservar y usar recompensa':'Seguir sumando visitas'} onPress={()=>router.push('/shop/'+p.shop_id as any)}/>}</Card>})}<Copy>Solo cuentan las visitas completadas mientras el programa esté activo. Los beneficios ganados se conservan si la barbería pausa la acumulación.</Copy></Screen>}
