/* eslint-disable react-hooks/set-state-in-effect -- Debounced address search lifecycle. */
import {useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Linking,Pressable,Text,View} from 'react-native';
import {searchAddresses,type AddressSuggestion} from '../lib/address-search';
import {Copy,Field,Failure,s} from './ui';
export default function AddressPicker({value,onChange,onSelect}:{value:string;onChange:(value:string)=>void;onSelect:(address:AddressSuggestion)=>void}){
 const [query,setQuery]=useState(''),[results,setResults]=useState<AddressSuggestion[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[searched,setSearched]=useState(false);const generation=useRef(0);
 useEffect(()=>{const id=++generation.current;const controller=new AbortController();setResults([]);setError('');setSearched(false);setBusy(false);if(query.trim().length<4)return()=>controller.abort();
 const timer=setTimeout(()=>{setBusy(true);const timeout=setTimeout(()=>controller.abort(),10000);void searchAddresses(query,controller.signal).then(data=>{if(id===generation.current){setResults(data);setSearched(true)}}).catch(()=>{if(id===generation.current)setError('No pudimos consultar direcciones. Revisa tu conexión y vuelve a escribir.')}).finally(()=>{clearTimeout(timeout);if(id===generation.current)setBusy(false)})},650);
 return()=>{++generation.current;clearTimeout(timer);controller.abort()};},[query]);
 return <View style={{gap:10}}><Field label="Dirección de tu barbería" value={value} placeholder="Calle, número y ciudad" autoCorrect={false} onChangeText={text=>{++generation.current;setResults([]);onChange(text);setQuery(text)}}/><Copy>Escribe al menos 4 letras y elige una dirección. Incluye el número y la ciudad para encontrar mejor tu local.</Copy>{busy&&<ActivityIndicator accessibilityLabel="Buscando direcciones" color="#163D2E"/>}<Failure message={error}/>{results.map(item=><Pressable key={item.id} accessibilityRole="button" onPress={()=>{++generation.current;setQuery('');setResults([]);onSelect(item)}} style={{padding:16,borderRadius:12,backgroundColor:'white',borderColor:'#DCE5DD',borderWidth:1,gap:5}}><Text style={s.label}>{item.address}</Text><Text>{item.label}</Text>{!item.precise&&<Copy>Ubicación aproximada de la calle; falta confirmar el local.</Copy>}</Pressable>)}{searched&&!results.length&&<Copy>No encontramos esa dirección. Prueba con calle, número, municipio y estado.</Copy>}<Pressable accessibilityRole="link" onPress={()=>void Linking.openURL('https://www.openstreetmap.org/copyright')}><Copy>Direcciones: OpenStreetMap · Búsqueda: Photon</Copy></Pressable></View>;
}
