import {useCallback,useRef,useState} from 'react';
import {ActivityIndicator,Text,View} from 'react-native';
import {useFocusEffect} from 'expo-router';
import {rpc} from '../lib/supabase';
import {money} from '../lib/types';
import {Button,Card,Choice,Copy,Failure,Field,s} from './ui';
type Appointment={id:string;customer_name:string;shop_name:string;barber_name:string;starts_at:string;status:string;deposit_cents:number;total_cents:number;payment_mode:string;payment_state:string|null;provider_live:boolean|null};
type Account={id:string;name:string;role:string|null;registered_at:string;email_confirmed:boolean;visits:number};
type Data={from:string;to:string;summary:Record<string,number>;appointment_count:number;account_count:number;appointments:Appointment[];accounts:Account[];activity:{id:string;action:string;created_at:string;note:string;actor:string}[]};
const statuses:Record<string,string>={'':'Todas',pending_payment:'Esperando pago',confirmed:'Confirmadas',arrived:'Llegaron',completed:'Completadas',cancelled:'Canceladas',no_show:'No asistieron'};
const actions:Record<string,string>={verify:'Barbería verificada',unverify:'Verificación retirada',suspend_shop:'Barbería suspendida',restore_shop:'Barbería restablecida',suspend_user:'Cuenta suspendida',restore_user:'Cuenta restablecida',reply:'Respuesta enviada',resolve:'Reporte resuelto',cancel_appointment:'Cita cancelada',hide_photo:'Foto retirada',hide_review:'Reseña retirada',activate_reserved_admin:'Administración activada'};
const date=(v:string)=>new Date(v).toLocaleString('es-MX');
export default function AdminDashboard(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [days,setDays]=useState(30),[page,setPage]=useState(0),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[tab,setTab]=useState('summary'),[customer,setCustomer]=useState<Account|null>(null);
 const request=useRef(0);
 const load=useCallback(async()=>{const id=++request.current;setBusy(true);setError('');setData(null);try{const result=await rpc<Data>('admin_dashboard',{p_days:days,p_page:page,p_search:query,p_status:status,p_customer:customer?.id??null});if(id===request.current)setData(result)}catch(e){if(id===request.current)setError((e as Error).message)}finally{if(id===request.current)setBusy(false)}},[days,page,query,status,customer]);
 useFocusEffect(useCallback(()=>{void load();return()=>{request.current++}},[load]));
 const count=tab==='accounts'?data?.account_count:data?.appointment_count;
 return <View style={{gap:16}}><Copy>Tu centro de control · solo administración</Copy>
 <View style={s.row}>{[[1,'24 horas'],[7,'7 días'],[30,'30 días']].map(([v,l])=><Choice key={v} label={String(l)} selected={days===v} onPress={()=>{setDays(Number(v));setPage(0)}}/>)}</View>
 <View style={s.row}>{[['summary','Resumen'],['accounts','Registros'],['appointments','Reservas'],['payments','Pagos'],['activity','Actividad']].map(([v,l])=><Choice key={v} label={l} selected={tab===v} onPress={()=>{setTab(v);setPage(0)}}/>)}</View>
 {['accounts','appointments','payments'].includes(tab)&&<><Field label="Buscar por nombre" placeholder="Cliente o barbería" value={search} onChangeText={setSearch} onSubmitEditing={()=>{setQuery(search.trim());setPage(0)}}/><Button secondary title="Buscar" onPress={()=>{setQuery(search.trim());setPage(0)}}/></>}
 {['appointments','payments'].includes(tab)&&<><View style={s.row}>{Object.entries(statuses).map(([v,l])=><Choice key={v} label={l} selected={status===v} onPress={()=>{setStatus(v);setPage(0)}}/>)}</View>{customer&&<Card><Copy>Historial de {customer.name} · últimos {days} días</Copy><Button secondary title="Ver todos los clientes" onPress={()=>{setCustomer(null);setPage(0)}}/></Card>}</>}
 <Failure message={error} onRetry={load}/>{busy&&<ActivityIndicator accessibilityLabel="Cargando panel"/>}
 {data&&<><Copy>Actualizado: {date(data.to)}. Los periodos usan la fecha de registro o creación de la reserva.</Copy>
 {tab==='summary'&&<><View style={s.row}>{[['accounts','Nuevos registros'],['owners','Nuevos dueños'],['appointments','Reservas creadas'],['completed','Completadas'],['cancelled','Canceladas'],['no_show','Inasistencias'],['shops','Barberías · total'],['pending_reports','Reportes pendientes · total']].map(([key,label])=><Card key={key} style={{flexGrow:1,flexBasis:'43%'}}><Text style={s.title}>{data.summary[key]}</Text><Copy>{label}</Copy></Card>)}</View><Copy>Revisa negocios, suspensiones y solicitudes en Gestión, debajo del resumen.</Copy></>}
 {tab==='accounts'&&<><Copy>Todos los registros · {data.account_count}. Incluye cuentas que aún no completan su perfil.</Copy>{data.accounts.map(a=><Card key={a.id}><Text style={s.heading}>{a.name}</Text><Copy>{a.role==='owner'?'Dueño de barbería':a.role==='client'?'Cliente':'Perfil pendiente'} · {a.email_confirmed?'Correo confirmado':'Correo pendiente'}</Copy><Copy>Registro: {date(a.registered_at)}{'\n'}Reservas como cliente: {a.visits}</Copy><Button secondary title="Ver reservas del cliente" disabled={a.role!=='client'} onPress={()=>{setCustomer(a);setTab('appointments');setPage(0);setQuery('');setSearch('');setStatus('')}}/></Card>)}</>}
 {tab==='payments'&&<><Card><Text style={s.heading}>Anticipos reales · MXN</Text><Copy>Cobrados: {money(data.summary.live_collected)}{'\n'}Devueltos: {money(data.summary.live_refunded)}{'\n'}Devoluciones pendientes o fallidas: {money(data.summary.live_refund_pending)}</Copy><Copy>Cohorte de pagos creados en el periodo. Una devolución puede haber ocurrido después del cobro. No incluye comisiones de Stripe ni equivale a tu saldo disponible.</Copy></Card><Card><Text style={s.heading}>Pruebas separadas</Text><Copy>Anticipos simulados: {money(data.summary.simulation)}{'\n'}Operaciones Stripe de prueba: {data.summary.test_payments}</Copy><Copy>Estos importes no son dinero cobrado. Comisiones de Pulso: todavía sin registro contable.</Copy></Card><Copy>El detalle y sus filtros aparecen debajo. Los totales anteriores abarcan todo el periodo.</Copy></>}
 {['appointments','payments'].includes(tab)&&data.appointments.map(a=><Card key={a.id}><Text style={s.pill}>{statuses[a.status]??a.status}</Text><Text style={s.heading}>{a.customer_name}</Text><Copy>{a.shop_name} · {a.barber_name}{'\n'}Cita: {date(a.starts_at)}</Copy><Copy>Total: {money(a.total_cents)} · Anticipo: {money(a.deposit_cents)}</Copy><Copy>{a.payment_mode==='simulation'?'SIMULACIÓN':a.payment_mode==='no_charge'?'Sin cobro':a.provider_live?'Stripe · real':'Stripe · prueba'}{a.payment_state?` · ${({paid:'Pagado',pending:'Pendiente',refunded:'Devuelto',refund_pending:'Devolución pendiente',refund_failed:'Devolución fallida',expired:'Expirado'} as Record<string,string>)[a.payment_state]??a.payment_state}`:''}</Copy></Card>)}
 {tab==='activity'&&<><Copy>Últimas 50 decisiones administrativas del periodo. Las aperturas, búsquedas y errores técnicos de la app todavía no se recopilan aquí.</Copy>{data.activity.map(a=><Card key={a.id}><Text style={s.heading}>{actions[a.action]??a.action}</Text><Copy>{a.actor} · {date(a.created_at)}</Copy><Copy>{a.note}</Copy></Card>)}{!data.activity.length&&<Copy>Aún no hay actividad administrativa en este periodo.</Copy>}</>}
 {['accounts','appointments','payments'].includes(tab)&&<>{count===0&&<Card><Copy>No hay resultados con estos filtros.</Copy></Card>}<View style={s.row}><Button title="Anterior" secondary disabled={page===0} onPress={()=>setPage(p=>p-1)}/><Copy>{page+1} / {Math.max(1,Math.ceil((count??0)/25))}</Copy><Button title="Siguiente" secondary disabled={(page+1)*25>=(count??0)} onPress={()=>setPage(p=>p+1)}/></View></>}
 <Button secondary title="Actualizar datos" onPress={load}/></>}
 </View>
}
