import {useEffect,useState} from 'react';
import {Alert,Text,View} from 'react-native';
import {db,rpc} from '../lib/supabase';
import {useAuth} from '../lib/auth';
import {uploadHaircutPhoto} from '../lib/photos';
import {Appointment} from '../lib/types';
import {PrivatePhoto} from './appointment-photo';
import {Button,Choice,Copy,Field,report,s} from './ui';
export default function HaircutRecord({a,owner=false}:{a:Appointment;owner?:boolean}){const {session}=useAuth();const [notes,setNotes]=useState('');const [path,setPath]=useState<string|null>(null);const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');useEffect(()=>{let active=true;void(async()=>{const r=await db().from('haircut_records').select('notes,photo_path,consent_at').eq('appointment_id',a.id).maybeSingle();if(active){if(r.error)setError(r.error.message);else{setNotes(r.data?.notes??'');setPath(r.data?.photo_path??null);setConsent(!!r.data?.consent_at)}}})();return()=>{active=false}},[a.id]);async function save(photo:string|null=path){await rpc('save_haircut',{p_id:a.id,p_notes:notes,p_photo:photo,p_consent:consent})}async function picture(camera:boolean){if(!session||!consent)return;setBusy(true);let uploaded:string|undefined;try{uploaded=await uploadHaircutPhoto(session.user.id,a.id,camera);if(!uploaded)return;await save(uploaded);if(path)await db().storage.from('haircut-records').remove([path]);setPath(uploaded)}catch(e){if(uploaded)await db().storage.from('haircut-records').remove([uploaded]);report(e)}finally{setBusy(false)}}if(!owner&&!path&&!notes)return null;return <View style={{gap:12}}><Text style={s.heading}>Así quedó este corte</Text>{error&&<Copy>{error}</Copy>}{path&&<PrivatePhoto path={path} bucket="haircut-records"/>}{owner?<><Field label="Detalles para la próxima visita" multiline maxLength={1000} placeholder="Degradado, número de máquina, largo y acabado…" value={notes} onChangeText={setNotes}/><Choice label="El cliente me autorizó a guardar la foto de su corte" selected={consent} onPress={()=>setConsent(!consent)}/><Copy>Solo este cliente y tu barbería pueden ver este registro. No se publica en la galería.</Copy><Button secondary title={path?'Cambiar foto del corte':'Añadir foto del corte'} disabled={busy||!consent} onPress={()=>Alert.alert('Foto del resultado','Elige cómo añadirla.',[{text:'Tomar foto',onPress:()=>picture(true)},{text:'Elegir de galería',onPress:()=>picture(false)},{text:'Cancelar',style:'cancel'}])}/><Button secondary title="Guardar detalles del corte" disabled={busy} onPress={async()=>{setBusy(true);try{await save();Alert.alert('Guardado','Los detalles estarán disponibles en la próxima visita.')}catch(e){report(e)}finally{setBusy(false)}}}/>{path&&<Button secondary title="Quitar foto del historial" disabled={busy} onPress={async()=>{setBusy(true);try{await save(null);await db().storage.from('haircut-records').remove([path]);setPath(null)}catch(e){report(e)}finally{setBusy(false)}}}/>}</>:<Copy>{notes}</Copy>}</View>}
