import {useClock} from '../lib/clock';
import {useEffect,useState} from 'react';
import {Alert,Modal,ScrollView,View} from 'react-native';
import {Appointment} from '../lib/types';
import {db,rpc} from '../lib/supabase';
import {localDay,nextDay} from '../lib/booking-helpers';
import {syncReminders} from '../lib/reminders';
import {Button,Choice,Copy,Failure,Screen,Title,report,s} from './ui';
export default function Reschedule({a,owner,onChange}:{a:Appointment;owner:boolean;onChange:()=>Promise<void>}){const now=useClock();const [open,setOpen]=useState(false);const [zone,setZone]=useState('America/Monterrey');const [day,setDay]=useState(localDay(new Date()));const [slots,setSlots]=useState<{starts_at:string}[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');useEffect(()=>{if(!open)return;let active=true;void (async()=>{try{const sh=await db().from('shops').select('timezone').eq('id',a.shop_id).single();if(sh.error)throw sh.error;const result=await rpc<{starts_at:string}[]>('reschedule_slots',{p_id:a.id,p_day:day});if(active){setZone(sh.data.timezone);setSlots(result);setError('')}}catch(e){if(active)setError((e as Error).message)}})();return()=>{active=false}},[open,day,a.id,a.shop_id]);function move(start:string){Alert.alert('Proponer nuevo horario',`Nuevo horario: ${new Date(start).toLocaleString('es-MX',{timeZone:zone})}. La otra persona deberá aceptar. Tu horario original sigue vigente.`,[{text:'Volver',style:'cancel'},{text:'Enviar propuesta',onPress:async()=>{setBusy(true);try{await rpc('propose_reschedule',{p_id:a.id,p_start:start,p_expected_start:a.starts_at});if(!owner)await syncReminders(a.customer_id).catch(()=>{});setOpen(false);await onChange()}catch(e){report(e)}finally{setBusy(false)}}}])}if(a.status!=='confirmed')return null;return <><Button secondary title="Proponer cambio de horario" disabled={now>Date.parse(a.starts_at)-a.cancel_hours*3600000} onPress={()=>{setSlots([]);setDay(localDay(new Date()));setOpen(true)}}/><Modal visible={open} presentationStyle="pageSheet" animationType="slide" onRequestClose={()=>setOpen(false)}><Screen><Title>Un nuevo momento.</Title><Copy>Se conserva tu reserva y su anticipo. La otra persona debe aceptar; el nuevo horario se revisará al aceptar. Puedes proponer cambios hasta {a.cancel_hours} horas antes.</Copy><Failure message={error}/><ScrollView horizontal contentContainerStyle={{gap:8}}>{Array.from({length:14},(_,i)=>{const d=nextDay(localDay(new Date(),zone),i);return <Choice key={d} label={d.slice(5)} selected={day===d} onPress={()=>{setSlots([]);setDay(d)}}/>})}</ScrollView><Copy>Zona horaria: {zone}</Copy><View style={s.row}>{slots.map(t=><Button key={t.starts_at} secondary title={new Date(t.starts_at).toLocaleTimeString('es-MX',{timeZone:zone,hour:'2-digit',minute:'2-digit'})} disabled={busy||Date.parse(t.starts_at)===Date.parse(a.starts_at)} onPress={()=>move(t.starts_at)}/>)}</View>{!slots.length&&<Copy>Sin horarios disponibles para este día.</Copy>}<Button secondary title="Volver" disabled={busy} onPress={()=>setOpen(false)}/></Screen></Modal></>}
