import {useClock} from '../lib/clock';
import {useCallback,useState} from 'react';
import {useFocusEffect} from 'expo-router';
import {Alert,View} from 'react-native';
import {useAuth} from '../lib/auth';
import {db,rpc} from '../lib/supabase';
import {type Appointment} from '../lib/types';
import {Button,Copy,report} from './ui';
type Proposal={id:string;requester:string;recipient:string;original_start:string;proposed_start:string;expires_at:string};
export default function RescheduleProposal({a,onChange}:{a:Appointment;onChange:()=>Promise<void>}){const {session}=useAuth();const now=useClock();const [item,setItem]=useState<Proposal|null>(null),[busy,setBusy]=useState(false);const load=useCallback(async()=>{const r=await db().from('reschedule_requests').select('*').eq('appointment_id',a.id).eq('status','pending').gt('expires_at',new Date().toISOString()).maybeSingle();if(!r.error)setItem(r.data)},[a.id]);useFocusEffect(useCallback(()=>{void load();const t=setInterval(()=>void load(),15000);return()=>clearInterval(t)},[load,a.starts_at]));if(!item||a.status!=='confirmed'||Date.parse(item.expires_at)<=now||Date.parse(item.original_start)!==Date.parse(a.starts_at))return null;const mine=item.requester===session?.user.id;function respond(action:string){Alert.alert(action==='accepted'?'Aceptar nuevo horario':'Responder propuesta',action==='accepted'?'El horario se cambiará solo si sigue disponible.':'Se conservará la cita original.',[{text:'Volver',style:'cancel'},{text:'Confirmar',onPress:async()=>{setBusy(true);try{await rpc('respond_reschedule',{p_request:item!.id,p_action:action});await load();await onChange()}catch(e){report(e)}finally{setBusy(false)}}}])}return <View style={{gap:10}}><Copy>{mine?'Esperando respuesta a tu propuesta':'Te proponen cambiar la cita'}: {new Date(item.proposed_start).toLocaleString('es-MX')} (hora de tu teléfono).</Copy><Copy>La cita original sigue vigente. La propuesta vence {new Date(item.expires_at).toLocaleString('es-MX')}.</Copy>{mine?<Button secondary title="Retirar propuesta" disabled={busy} onPress={()=>respond('cancelled')}/>:<><Button title="Aceptar nuevo horario" disabled={busy} onPress={()=>respond('accepted')}/><Button secondary title="Conservar horario original" disabled={busy} onPress={()=>respond('declined')}/></>}</View>}
