import {router} from 'expo-router';
import {useEffect,useState} from 'react';
import {Text,View} from 'react-native';
import {db,rpc} from '../lib/supabase';
import {uploadAppointmentPhoto} from '../lib/photos';
import {type Appointment} from '../lib/types';
import {PrivatePhoto} from './appointment-photo';
import {Button,Choice,Copy,Field,report,s} from './ui';
export default function Review({appointment}:{appointment:Appointment}){const [rating,setRating]=useState(5);const [comment,setComment]=useState('');const [photo,setPhoto]=useState<string|null>(null);const [saved,setSaved]=useState<number|null>(null);const [busy,setBusy]=useState(true);const [error,setError]=useState('');
useEffect(()=>{let active=true;void (async()=>{const r=await db().from('reviews').select('rating,comment,photo_path').eq('appointment_id',appointment.id).maybeSingle();if(active){if(r.error)setError(r.error.message);else if(r.data){setSaved(r.data.rating);setComment(r.data.comment);setPhoto(r.data.photo_path)}setBusy(false)}})();return()=>{active=false}},[appointment.id]);
async function save(){setBusy(true);try{await rpc('submit_review',{p_id:appointment.id,p_rating:rating,p_comment:comment,p_photo:photo});setSaved(rating)}catch(e){report(e)}finally{setBusy(false)}}
return <View style={{gap:12}}><Text style={s.heading}>{saved?'Tu valoración: '+saved+' ★':'¿Qué tal estuvo tu corte?'}</Text>{error?<Copy>{error}</Copy>:saved?<Copy>{comment}</Copy>:<><Copy>Comparte tu experiencia. Tu nombre de pila, comentario y foto serán visibles en el perfil de la barbería. Se guarda una sola vez.</Copy><View style={s.row}>{[1,2,3,4,5].map(n=><Choice key={n} label={n+' ★'} selected={rating===n} onPress={()=>setRating(n)}/>)}</View><Field label="Tu experiencia (opcional)" multiline maxLength={1000} value={comment} onChangeText={setComment}/><Button secondary title={photo?'Cambiar foto':'Añadir foto del resultado'} disabled={busy} onPress={async()=>{setBusy(true);try{const p=await uploadAppointmentPhoto(appointment.customer_id,appointment.id,'review');if(p){if(photo)await db().storage.from('appointment-media').remove([photo]);setPhoto(p)}}catch(e){report(e)}finally{setBusy(false)}}}/>{photo&&<Button secondary title="Quitar foto" disabled={busy} onPress={async()=>{await db().storage.from('appointment-media').remove([photo]);setPhoto(null)}}/>}<Button title="Publicar valoración" disabled={busy} onPress={save}/></>}{photo&&<PrivatePhoto path={photo}/>}</View>}
export function ShopReviews({shop}:{shop:string}){const [rows,setRows]=useState<{appointment_id:string;rating:number;comment:string;photo_path:string|null;author:string}[]>([]);const [error,setError]=useState('');useEffect(()=>{let active=true;rpc<typeof rows>('shop_reviews',{p_shop:shop}).then(r=>{if(active)setRows(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[shop]);return <View style={{gap:16}}><Text style={s.heading}>Reseñas de visitas verificadas</Text>{error?<Copy>{error}</Copy>:!rows.length?<Copy>Esta barbería todavía no tiene reseñas.</Copy>:rows.map(r=><View key={r.appointment_id} style={{gap:8}}><Text style={s.heading}>{r.author} · {r.rating} ★</Text>{!!r.comment&&<Copy>{r.comment}</Copy>}{r.photo_path&&<PrivatePhoto path={r.photo_path}/>}<Button secondary title="Reportar reseña o su fotografía" onPress={()=>router.push({pathname:'/support',params:{kind:'review',target:r.appointment_id}})}/></View>)}</View>}
