import {Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View,type TextInputProps,type ViewStyle} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {useSegments} from 'expo-router';
import Ionicons from '@expo/vector-icons/Ionicons';
import type {ReactNode,ComponentProps} from 'react';
export const colors={bg:'#F5F6F3',ink:'#142C23',muted:'#68766F',line:'#E3E9E3',green:'#163D2E',lime:'#D6F58A',white:'#FFFFFF'};
export function Screen({children}:{children:ReactNode}){const insets=useSafeAreaInsets();const segments=useSegments();const top=segments[0]==='(tabs)'||segments[0]==='login';return <ScrollView style={s.screen} contentContainerStyle={[s.content,{paddingTop:top?insets.top+22:20}]} keyboardShouldPersistTaps="handled">{children}</ScrollView>}
export function Title({children}:{children:ReactNode}){return <Text accessibilityRole="header" style={s.title}>{children}</Text>}
export function Copy({children}:{children:ReactNode}){return <Text style={s.copy}>{children}</Text>}
export function Card({children,style}:{children:ReactNode;style?:ViewStyle}){return <View style={[s.card,style]}>{children}</View>}
export function Button({title,onPress,disabled=false,secondary=false}:{title:string;onPress:()=>void;disabled?:boolean;secondary?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,secondary&&s.secondary,disabled&&{opacity:.45},pressed&&{opacity:.8,transform:[{scale:.99}]}]}><Text style={[s.buttonText,secondary&&{color:colors.ink}]}>{title}</Text></Pressable>}
export function Field({label,...props}:TextInputProps&{label:string}){return <View style={{gap:8}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor="#84938A" style={s.input} {...props}/></View>}
export function Choice({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable accessibilityRole="checkbox" accessibilityState={{checked:selected}} onPress={onPress} style={[s.choice,selected&&{backgroundColor:'#EFF8DF',borderColor:colors.green}]}><Ionicons name={selected?'checkmark-circle':'ellipse-outline'} size={22} color={selected?colors.green:colors.muted}/><Text style={[s.label,{flexShrink:1}]}>{label}</Text></Pressable>}
export function Failure({message,onRetry}:{message:string;onRetry?:()=>void}){if(!message)return null;return <View style={s.error}><Text style={{color:'#8b402c'}}>{message}</Text>{onRetry&&<Button title="Reintentar" onPress={onRetry} secondary/>}</View>}
export function Brand({business=false}:{business?:boolean}){return <View style={{flexDirection:'row',alignItems:'center',gap:10}}><View style={{width:35,height:35,borderRadius:12,backgroundColor:colors.green,justifyContent:'center',alignItems:'center'}}><Ionicons name="pulse" size={24} color={colors.lime}/></View><Text style={{fontSize:27,fontWeight:'800',letterSpacing:-1.3,color:colors.ink}}>pulso<Text style={{color:'#719C42'}}>.</Text></Text>{business&&<Text style={s.pill}>BARBERÍA</Text>}</View>}
export function MenuRow({icon,title,subtitle,onPress}:{icon:ComponentProps<typeof Ionicons>['name'];title:string;subtitle:string;onPress:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[s.menu,pressed&&{opacity:.65}]}><View style={s.iconTile}><Ionicons name={icon} color={colors.green} size={24}/></View><View style={{flex:1,gap:4}}><Text style={{fontSize:16,fontWeight:'700',color:colors.ink}}>{title}</Text><Text style={s.muted}>{subtitle}</Text></View><Ionicons name="chevron-forward" color={colors.muted} size={18}/></Pressable>}
export function Empty({icon,title,body}:{icon:ComponentProps<typeof Ionicons>['name'];title:string;body:string}){return <Card style={{alignItems:'center',paddingVertical:30}}><View style={s.iconTile}><Ionicons name={icon} size={28} color={colors.green}/></View><Text style={[s.heading,{textAlign:'center'}]}>{title}</Text><Text style={[s.copy,{textAlign:'center'}]}>{body}</Text></Card>}
export function report(e:unknown){Alert.alert('Pulso',e instanceof Error?e.message:(e as any)?.message||'No pudimos completar la acción.')}
export const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},content:{padding:22,gap:20,paddingBottom:36},title:{fontSize:32,fontWeight:'800',letterSpacing:-1.1,color:colors.ink,lineHeight:38},copy:{fontSize:15,color:colors.muted,lineHeight:23},card:{padding:20,backgroundColor:'white',borderRadius:24,borderWidth:1,borderColor:colors.line,gap:14},button:{backgroundColor:colors.green,paddingVertical:17,paddingHorizontal:20,borderRadius:18,alignItems:'center',minHeight:55,justifyContent:'center'},buttonText:{fontSize:16,fontWeight:'700',color:'white'},secondary:{backgroundColor:'#E9EEE7'},label:{fontSize:14,fontWeight:'600',color:colors.ink},input:{fontSize:16,minHeight:55,padding:16,borderWidth:1,borderColor:colors.line,borderRadius:16,backgroundColor:'white',color:colors.ink},choice:{padding:15,borderRadius:17,borderWidth:1,borderColor:colors.line,backgroundColor:'white',minHeight:52,flexDirection:'row',gap:10,alignItems:'center'},row:{flexDirection:'row',alignItems:'center',gap:10,flexWrap:'wrap'},heading:{fontSize:21,fontWeight:'700',letterSpacing:-.5,color:colors.ink},error:{padding:15,backgroundColor:'#fae9e1',borderRadius:16,gap:12},photo:{width:'100%',height:200,borderRadius:18},muted:{fontSize:13,color:colors.muted,lineHeight:19},pill:{color:colors.green,backgroundColor:colors.lime,paddingVertical:6,paddingHorizontal:10,borderRadius:20,fontSize:10,fontWeight:'800',letterSpacing:.8,alignSelf:'flex-start'},menu:{flexDirection:'row',alignItems:'center',gap:14,paddingVertical:12},iconTile:{width:50,height:50,borderRadius:17,backgroundColor:'#EFF4E7',justifyContent:'center',alignItems:'center'}});
