import BookingSection from '../../components/booking-section';
import {useCallback,useState} from 'react';
import {Alert,Linking,Pressable,Text,View} from 'react-native';
import {router,useFocusEffect} from 'expo-router';
import Ionicons from '@expo/vector-icons/Ionicons';
import {useAuth,saveProfile} from '../../lib/auth';
import {db,rpc} from '../../lib/supabase';
import {emptyDetails,validClabe,AccountDetails} from '../../lib/account-details';
import ReminderSettings from '../../components/reminder-settings';
import {clearReminders} from '../../lib/reminders';
import {enablePush} from '../../lib/push';
import {Brand,Button,Card,Choice,Copy,Failure,Field,MenuRow,Screen,Title,report,s,colors} from '../../components/ui';
export default function Account(){
 const [panel,setPanel]=useState<string|null>(null);const {session,profile,refresh,error}=useAuth();const [admin,setAdmin]=useState(false);const [messages,setMessages]=useState<any[]>([]);const [name,setName]=useState('');const [details,setDetails]=useState({...emptyDetails});const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState('');const owner=profile?.role==='owner';
 useFocusEffect(useCallback(()=>{let active=true;setName(profile?.name??'');setLoading(true);void(async()=>{if(!session)return;try{const isAdmin=await rpc<boolean>('is_admin');if(active)setAdmin(isAdmin);const q=await db().from('account_details').select('*').eq('user_id',session.user.id).maybeSingle();if(q.error)throw q.error;if(active){setDetails(q.data??{...emptyDetails});setLoadError('')}if(profile?.role==='client'){const r=await db().from('inbox').select('id,created_at,promotions(title,body,shops(name))').eq('customer_id',session.user.id).order('created_at',{ascending:false}).limit(50);if(r.error)throw r.error;if(active)setMessages(r.data??[])}}catch(e){if(active)setLoadError((e as Error).message)}finally{if(active)setLoading(false)}})();return()=>{active=false}},[session?.user.id,profile?.name,profile?.role]));
 const change=(key:keyof Omit<AccountDetails,'user_id'>,value:string)=>setDetails(d=>({...d,[key]:value}));
 async function save(){if(!profile||!session)return;if(details.paypal_email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(details.paypal_email)){report(Error('Revisa el correo de PayPal.'));return}if(owner&&details.bank_clabe&&(!validClabe(details.bank_clabe)||!details.bank_name.trim()||!details.account_holder.trim())){report(Error('Revisa la CLABE de 18 dígitos, el banco y el titular.'));return}setBusy(true);try{await saveProfile(profile.id,name,profile.role);const r=await db().from('account_details').upsert({...details,user_id:session.user.id,...(!owner?{bank_name:'',bank_clabe:'',account_holder:''}:{})});if(r.error)throw r.error;await refresh();Alert.alert('Datos guardados','Tu perfil y tus preferencias se actualizaron. Los pagos reales aún no están activados.')}catch(e){report(e)}finally{setBusy(false)}}
 async function logout(){setBusy(true);try{await clearReminders();await db().from('push_tokens').delete().eq('user_id',session!.user.id);const r=await db().auth.signOut();if(r.error)throw r.error}catch(e){report(e)}finally{setBusy(false)}}
 return <Screen><Brand business={owner}/><Title>Tu espacio en Pulso.</Title><Failure message={error||loadError} onRetry={refresh}/>{session&&profile&&<>
 <View style={{backgroundColor:colors.green,borderRadius:28,padding:24,gap:12}}><View style={[s.row,{alignItems:'center'}]}><View style={{width:62,height:62,borderRadius:31,backgroundColor:colors.lime,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:25,fontWeight:'800',color:colors.green}}>{profile.name.trim().slice(0,2).toUpperCase()}</Text></View><View style={{flex:1,gap:4}}><Text style={{fontSize:23,fontWeight:'800',color:'white'}}>{profile.name}</Text><Text style={{color:'#D6E3DA'}}>{owner?'Mi negocio, mi estilo':'Tu estilo empieza aquí'}</Text></View></View><Text style={{color:'#D6E3DA'}}>{session.user.email}</Text><Text style={{color:colors.lime,fontWeight:'700'}}>{owner?'CUENTA DE BARBERÍA':'CUENTA DE CLIENTE'}</Text></View>
 <BookingSection step="01" title="Información personal" summary="Nombre, teléfono y preferencias" open={panel==='personal'} onToggle={()=>setPanel(v=>v==='personal'?null:'personal')}><Field label="Nombre" value={name} maxLength={80} onChangeText={setName}/><Field label="Teléfono (opcional)" keyboardType="phone-pad" value={details.phone} maxLength={30} onChangeText={v=>change('phone',v)}/><Field label="Ciudad (opcional)" value={details.city} maxLength={100} onChangeText={v=>change('city',v)}/><Field label={owner?'Sobre ti (opcional)':'Mis preferencias de corte (opcional)'} multiline value={details.bio} maxLength={300} onChangeText={v=>change('bio',v)}/><Copy>Estos datos son privados de tu cuenta. No se publican en el ranking.</Copy></BookingSection>
 <BookingSection step="02" title={owner?'Datos para recibir pagos':'Preferencia de pago'} summary={details.payment_method==='paypal'?'PayPal':'Cuenta bancaria'} open={panel==='payment'} onToggle={()=>setPanel(v=>v==='payment'?null:'payment')}><View style={s.row}><Ionicons name="wallet-outline" size={25} color={colors.green}/><Text style={s.heading}>{owner?'Dónde recibir tus pagos':'Método de pago preferido'}</Text></View><View style={s.row}><Choice label="PayPal" selected={details.payment_method==='paypal'} onPress={()=>change('payment_method','paypal')}/><Choice label="Cuenta bancaria" selected={details.payment_method==='bank'} onPress={()=>change('payment_method','bank')}/></View>{details.payment_method==='paypal'?<Field label="Correo de PayPal (opcional)" autoCapitalize="none" autoCorrect={false} keyboardType="email-address" value={details.paypal_email} maxLength={254} onChangeText={v=>change('paypal_email',v.trim())}/>:owner?<><Field label="Banco" value={details.bank_name} maxLength={80} onChangeText={v=>change('bank_name',v)}/><Field label="Titular de la cuenta" value={details.account_holder} maxLength={100} onChangeText={v=>change('account_holder',v)}/><Field label="CLABE (18 dígitos)" secureTextEntry keyboardType="number-pad" value={details.bank_clabe} maxLength={18} onChangeText={v=>change('bank_clabe',v.replace(/\D/g,''))}/></>:<Copy>Guardaremos tu preferencia de pagar mediante cuenta bancaria. No necesitas introducir números de tarjeta ni contraseñas.</Copy>}<Copy>{owner?'Datos de cobro sin verificar. Guardarlos no conecta tu cuenta ni habilita depósitos.':'Esta es una preferencia; todavía no conecta ni cobra a tu cuenta.'} Los anticipos reales requieren conectar y habilitar los cobros del negocio.</Copy></BookingSection>
 {panel&&<Button title={busy?'Guardando…':'Guardar mi perfil'} disabled={busy||loading||!!loadError||!name.trim()} onPress={save}/>}
 <Card>{owner?<><MenuRow icon="trophy-outline" title="Mi lugar en el ranking" subtitle="Municipio, estado y nacional" onPress={()=>router.push('/ranking')}/><MenuRow icon="storefront-outline" title="Administrar mi barbería" subtitle="Fotos, servicios y equipo" onPress={()=>router.push('/business')}/></>:<><MenuRow icon="notifications-outline" title="Avisos y lista de espera" subtitle="Cambios y horarios liberados" onPress={()=>router.push('/waitlist')}/><MenuRow icon="gift-outline" title="Mis recompensas" subtitle="Tus visitas tienen premio" onPress={()=>router.push('/rewards')}/></>}</Card>
 {!owner&&<><ReminderSettings/><Button secondary title="Activar notificaciones" onPress={async()=>{try{await enablePush(session.user.id);Alert.alert('Notificaciones activadas','Recibirás promociones de las barberías a las que hayas dado permiso.')}catch(e){report(e)}}}/>{messages.length>0&&<><Text style={s.heading}>Novedades para ti</Text>{messages.map(m=><Card key={m.id}><Text style={s.pill}>{m.promotions?.shops?.name}</Text><Text style={s.heading}>{m.promotions?.title}</Text><Copy>{m.promotions?.body}</Copy></Card>)}</>}</>}
 <Card><MenuRow icon="help-circle-outline" title="Ayuda y reportes" subtitle="Consulta tus solicitudes" onPress={()=>router.push('/support')}/><MenuRow icon="notifications-outline" title="Avisos de mis citas" subtitle="Reservas, cambios y recordatorios" onPress={()=>router.push('/notifications')}/>{admin&&<MenuRow icon="shield-checkmark-outline" title="Administración de Pulso" subtitle="Registros, reservas, pagos y reportes" onPress={()=>router.push('/admin')}/>}</Card><Button secondary title="Activar avisos de citas" onPress={async()=>{try{await enablePush(session.user.id);Alert.alert('Listo','Notificaciones activadas en este dispositivo.')}catch(e){report(e)}}}/>{owner&&<Button secondary title="Conectar cobros de mi barbería" onPress={async()=>{try{const r=await db().functions.invoke('payment-onboarding');if(r.error)throw r.error;if(r.data.error)throw Error(r.data.error);await Linking.openURL(r.data.url)}catch(e){report(e)}}}/>}<Button secondary title="Probar aviso con la app cerrada" onPress={async()=>{try{await rpc('test_push');Alert.alert('Prueba en cola','Cierra Pulso y espera unos minutos. Si no llega, revisaremos los permisos y la configuración.')}catch(e){report(e)}}}/><Button secondary title="Cerrar sesión" disabled={busy} onPress={logout}/><Pressable accessibilityRole="button" style={{alignSelf:'center',padding:12}} onPress={()=>router.push('/delete-account')}><Text style={{color:colors.muted,fontSize:12,textDecorationLine:'underline'}}>Eliminar mi cuenta</Text></Pressable>
 </>}</Screen>
}
