import {useCallback,useRef,useState} from 'react';
import {ActivityIndicator,Image,Modal,Pressable,Text,View} from 'react-native';
import {router,useFocusEffect} from 'expo-router';
import Ionicons from '@expo/vector-icons/Ionicons';
import {db,photoURL,rpc} from '../../lib/supabase';
import {useAuth} from '../../lib/auth';
import {Button,Card,Choice,Copy,Empty,Failure,Screen,Title,colors,s} from '../../components/ui';
type Rank={shop_id:string;name:string;municipality:string;state:string;country:string;visits:number;rating:number|null;reviews:number;score:number;position:number};
type Region={country:string;state:string;municipality:string};
const medals=['#D4A52C','#A7B2BF','#B97A49'];
export default function Ranking(){const {profile,session}=useAuth();const owner=profile?.role==='owner';const [regions,setRegions]=useState<Region[]>([]);const [scope,setScope]=useState('municipality');const [state,setState]=useState('');const [municipality,setMunicipality]=useState('');const [rows,setRows]=useState<Rank[]>([]);const [own,setOwn]=useState('');const [photos,setPhotos]=useState<Record<string,string>>({});const [busy,setBusy]=useState(true);const [error,setError]=useState('');const [picker,setPicker]=useState<'state'|'municipality'|null>(null);const generation=useRef(0);
 const load=useCallback(async()=>{const gen=++generation.current;setBusy(true);try{const places=await rpc<Region[]>('ranking_regions');let myShop:{id:string;state:string;municipality:string}|null=null;if(owner){const sh=await db().from('shops').select('id,state,municipality').eq('owner_id',session!.user.id).maybeSingle();if(sh.error)throw sh.error;myShop=sh.data}const mexico=places.filter(p=>p.country==='México');const selectedState=state||myShop?.state||mexico[0]?.state||'';const selectedMunicipality=municipality||((myShop?.state===selectedState&&myShop.municipality)||mexico.find(p=>p.state===selectedState)?.municipality||'');const result=await rpc<Rank[]>('shop_rankings',{p_scope:scope,p_country:'México',p_state:selectedState,p_municipality:selectedMunicipality});const covers=await db().from('photos').select('shop_id,storage_path').eq('kind','shop').in('shop_id',result.map(r=>r.shop_id)).order('created_at',{ascending:false});if(gen!==generation.current)return;setRegions(mexico);setRows(result);setOwn(myShop?.id??'');const images:Record<string,string>={};for(const p of covers.data??[])images[p.shop_id]??=photoURL(p.storage_path);setPhotos(images);if(!state)setState(selectedState);if(!municipality)setMunicipality(selectedMunicipality);setError('')}catch(e){if(gen===generation.current){setError((e as Error).message);setRows([])}}finally{if(gen===generation.current)setBusy(false)}},[scope,state,municipality,owner,session]);
 useFocusEffect(useCallback(()=>{void load();return()=>{generation.current++}},[load]));const unique=(v:string[])=>[...new Set(v)].filter(Boolean).sort((a,b)=>a.localeCompare(b));const options=picker==='state'?unique(regions.map(r=>r.state)):unique(regions.filter(r=>r.state===state).map(r=>r.municipality));const mine=rows.find(r=>r.shop_id===own);
 return <><Screen><View style={{backgroundColor:colors.green,padding:25,borderRadius:28,gap:8}}><Ionicons name="trophy" size={40} color={medals[0]}/><Text style={{color:colors.lime,fontSize:12,fontWeight:'800',letterSpacing:2}}>RANKING PULSO</Text><Text style={{color:'white',fontSize:30,fontWeight:'800'}}>Los mejores estilos.</Text><Text style={{color:'#D4E2D8'}}>Encuentra a los favoritos de tu zona.</Text></View>
 <View style={s.row}>{[['municipality','Municipio'],['state','Estado'],['country','Nacional']].map(([v,label])=><Choice key={v} label={label} selected={scope===v} onPress={()=>setScope(v)}/>)}</View>
 {scope!=='country'&&<Pressable accessibilityRole="button" onPress={()=>setPicker('state')} style={[s.row,{backgroundColor:'white',padding:18,borderRadius:16,justifyContent:'space-between'}]}><Text style={s.heading}>{state||'Seleccionar estado'}</Text><Ionicons name="chevron-down" size={20} color={colors.green}/></Pressable>}{scope==='municipality'&&<Pressable accessibilityRole="button" onPress={()=>setPicker('municipality')} style={[s.row,{backgroundColor:'white',padding:18,borderRadius:16,justifyContent:'space-between'}]}><Text style={s.heading}>{municipality||'Seleccionar municipio'}</Text><Ionicons name="chevron-down" size={20} color={colors.green}/></Pressable>}
 {owner&&<Card><Text style={s.heading}>Tu barbería</Text><Copy>{mine?`Puesto #${mine.position} · ${mine.name}`:busy?'Buscando tu posición…':own?'Tu barbería todavía no aparece en esta clasificación. Revisa tu zona y completa tus primeras visitas.':'Registra tu barbería para participar.'}</Copy></Card>}
 <Failure message={error} onRetry={load}/>{busy?<ActivityIndicator color={colors.green}/>:rows.length?rows.map(r=>{const position=Number(r.position);const podium=position<=3;return <Pressable key={r.shop_id} accessibilityRole="button" disabled={owner} onPress={()=>router.push({pathname:'/shop/[id]',params:{id:r.shop_id}})}><View style={{backgroundColor:r.shop_id===own?'#EFF7E2':'white',padding:18,borderRadius:22,borderWidth:podium?1.5:1,borderColor:podium?medals[position-1]:colors.line,gap:12}}><View style={[s.row,{alignItems:'center',flexWrap:'nowrap'}]}><View style={{width:46,alignItems:'center',gap:4}}>{podium?<Ionicons name="trophy" size={32} color={medals[position-1]}/>:<Text style={{fontSize:23,fontWeight:'800',color:colors.green}}>#{position}</Text>}{podium&&<Text style={{fontSize:12,fontWeight:'800',color:colors.ink}}>#{position}</Text>}</View>{photos[r.shop_id]?<Image source={{uri:photos[r.shop_id]}} style={{height:58,width:58,borderRadius:16}}/>:<View style={{height:58,width:58,borderRadius:16,backgroundColor:'#EDF2EC',alignItems:'center',justifyContent:'center'}}><Ionicons name="cut-outline" size={27} color={colors.green}/></View>}<View style={{flex:1,gap:5}}><Text style={{fontSize:18,fontWeight:'800',color:colors.ink}}>{r.name}</Text><Text style={s.muted}>{r.municipality} · {r.state}</Text></View>{!owner&&<Ionicons name="chevron-forward" size={18} color={colors.muted}/>}</View><View style={[s.row,{justifyContent:'space-between'}]}><Text style={{fontWeight:'700',color:colors.green}}>{r.rating===null?'Estrenando su lugar':`★ ${Number(r.rating).toFixed(1)} · ${r.reviews} reseñas`}</Text><Text style={s.muted}>{r.visits} cortes</Text></View>{r.shop_id===own&&<Text style={{color:colors.green,fontWeight:'700'}}>TU BARBERÍA</Text>}</View></Pressable>}):!error&&<Empty icon="trophy-outline" title="Aquí empieza el ranking" body="Las barberías de esta zona aparecerán después de sus primeras visitas completadas."/>}</Screen>
 <Modal visible={!!picker} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setPicker(null)}><Screen><Title>{picker==='state'?'Selecciona el estado':'Selecciona el municipio'}</Title>{options.map(v=><Button key={v} secondary title={v} onPress={()=>{if(picker==='state'){setState(v);setMunicipality('')}else setMunicipality(v);setPicker(null)}}/>)}{!options.length&&<Copy>Todavía no hay barberías registradas en esta zona.</Copy>}<Button secondary title="Volver" onPress={()=>setPicker(null)}/></Screen></Modal></>
}
