import {useAuth} from '../../lib/auth';
import ShopShare from '../../components/shop-share';
import {useEffect,useState} from 'react';
import {Image,Text,View} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import {rpc,photoURL} from '../../lib/supabase';
import {Shop,Photo,Service,Barber,money} from '../../lib/types';
import {ShopTabs,ShopSectionContent,type ShopTab} from '../../components/shop-sections';
import {Button,Card,Copy,Failure,Screen,Title,s} from '../../components/ui';
export default function GuestShop(){const {profile}=useAuth();const owner=profile?.role==='owner';const {id}=useLocalSearchParams<{id:string}>();const [tab,setTab]=useState<ShopTab>('services');const [data,setData]=useState<{shops:Shop[];photos:Photo[];services:Service[];barbers:Barber[]}|null>(null);const [error,setError]=useState('');useEffect(()=>{let active=true;rpc<typeof data>('public_catalog',{p_shop:id}).then(r=>{if(active)setData(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[id]);const shop=data?.shops[0];const cover=data?.photos.find(p=>p.kind==='shop');return <Screen footer={!owner&&shop&&<Button title="Entrar para reservar" onPress={()=>router.push('/login')}/>}><Failure message={error}/>{shop&&data?<>{cover&&<Image source={{uri:photoURL(cover.storage_path)}} style={[s.photo,{height:195}]}/>}<Title>{shop.name}</Title><ShopShare id={shop.id} name={shop.name}/>{shop.verified&&<Text style={s.pill}>✓ BARBERÍA VERIFICADA</Text>}<Copy>{shop.address} · {shop.municipality}</Copy><Copy>{shop.description}</Copy><Copy>{shop.days.map(d=>['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'][d]).join(', ')} · {shop.open_hour}:00–{shop.close_hour}:00</Copy>{!owner&&<Button secondary title="♡ Guardar en favoritas" onPress={()=>router.push('/login')}/>}<ShopTabs value={tab} onChange={setTab}/><ShopSectionContent tab={tab} shop={shop.id} photos={data.photos} barbers={data.barbers} guest readOnly={owner}/>{tab==='services'&&<View style={{gap:12}}>{data.services.map(v=><Card key={v.id}><Text style={s.heading}>{v.name}</Text><Text style={s.pill}>{money(v.price_cents)} · {v.duration_minutes} min</Text><Copy>{v.description}</Copy></Card>)}{!data.services.length&&<Copy>Esta barbería aún no ha publicado servicios.</Copy>}</View>}</>:<Copy>{data?'Este local no está disponible.':'Cargando barbería…'}</Copy>}</Screen>}
