import BookingSection from '../../components/booking-section';
import * as Crypto from 'expo-crypto';
import Verified from '../../components/verified';
import {useClock} from '../../lib/clock';
/* eslint-disable react-hooks/set-state-in-effect -- Clear stale availability immediately when its selection changes. */
import {useEffect,useRef,useState} from 'react';
import {Alert,Image,Linking,Modal,ScrollView,Text,View} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import {useAuth} from '../../lib/auth';
import {db,photoURL,rpc} from '../../lib/supabase';
import {money,quote,type Offer,offerDiscount,type Shop,type Service,type Barber,type Photo,type Appointment,type LoyaltyProgram,type LoyaltyReward} from '../../lib/types';
import {localDay,nextDay,repeatSelection} from '../../lib/booking-helpers';
import Directions from '../../components/directions';
import {ShopTabs,ShopSectionContent,type ShopTab} from '../../components/shop-sections';
import {syncReminders} from '../../lib/reminders';
import {Button,Card,Choice,Copy,Failure,Screen,Title,report,s,colors} from '../../components/ui';
export default function ShopProfile(){
 const {id,repeat,service:seedService,barber:seedBarber,start:seedStart}=useLocalSearchParams<{id:string;repeat?:string;service?:string;barber?:string;start?:string}>();
 const [tab,setTab]=useState<ShopTab>('services');const [reviewOpen,setReviewOpen]=useState(false);const scroll=useRef<ScrollView>(null);const bookingY=useRef(0);
 const [section,setSection]=useState<string|null>(null);
 const toggleSection=(name:string)=>setSection(value=>value===name?null:name);
 const now=useClock();const {session,profile}=useAuth();const [shop,setShop]=useState<Shop|null>(null);const [services,setServices]=useState<Service[]>([]);const [barbers,setBarbers]=useState<Barber[]>([]);const [photos,setPhotos]=useState<Photo[]>([]);const [fav,setFav]=useState(false);const [consent,setConsent]=useState(false);const [cut,setCut]=useState('');const [extras,setExtras]=useState<string[]>([]);const [barber,setBarber]=useState('');const [day,setDay]=useState(()=>localDay(new Date()));const [slots,setSlots]=useState<{starts_at:string;ends_at:string}[]>([]);const [slot,setSlot]=useState('');const [slotBusy,setSlotBusy]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [accept,setAccept]=useState(false);const [note,setNote]=useState('');const [rewards,setRewards]=useState<LoyaltyReward[]>([]);const [rewardId,setRewardId]=useState('');const [program,setProgram]=useState<LoyaltyProgram|null>(null);const wantedSlot=useRef('');const [offers,setOffers]=useState<Offer[]>([]);const [offerId,setOfferId]=useState('');const [paidMode,setPaidMode]=useState(false);const requestId=useRef(Crypto.randomUUID());
 useEffect(()=>{let active=true;(async()=>{try{
  const results=await Promise.all([db().from('shops').select('*').eq('id',id).single(),db().from('services').select('*').eq('shop_id',id).eq('active',true),db().from('barbers').select('*').eq('shop_id',id).eq('active',true),db().from('photos').select('*').eq('shop_id',id).order('created_at',{ascending:false}),db().from('favorites').select('shop_id').eq('shop_id',id).eq('customer_id',session!.user.id).maybeSingle(),db().from('marketing_consents').select('enabled').eq('shop_id',id).eq('customer_id',session!.user.id).maybeSingle(),db().from('loyalty_rewards').select('*').eq('shop_id',id).eq('customer_id',session!.user.id).is('used_appointment_id',null),db().from('loyalty_programs').select('*').eq('shop_id',id).maybeSingle(),db().from('offers').select('*').eq('shop_id',id).eq('active',true).gt('ends_at',new Date().toISOString())]);
  for(const r of results)if(r.error)throw r.error;if(!active)return;
  const ready=await rpc<boolean>('payment_ready',{p_shop:id});if(active)setPaidMode(ready);const sh=results[0].data as Shop;const ss=(results[1].data??[]) as Service[];const bs=(results[2].data??[]) as Barber[];
  let selection={cut:ss.find(x=>x.kind==='cut')?.id??'',extras:[] as string[],barber:bs[0]?.id??''};let message='';
  if(repeat){const previous=await db().from('appointments').select('*').eq('id',repeat).eq('customer_id',session!.user.id).eq('shop_id',id).eq('status','completed').single();if(previous.error)throw Error('No se encontró un corte completado de tu cuenta en esta barbería.');const chosen=repeatSelection(previous.data as Appointment,ss,bs);selection=chosen;message=chosen.missing?'Parte de tu corte anterior ya no está disponible. Revisa el servicio, los extras y el barbero antes de continuar.':'Recuperamos tu corte, extras y barbero. Elige un nuevo horario y revisa los precios actuales.'}
  else if(seedService){selection.cut=ss.some(x=>x.id===seedService&&x.kind==='cut')?seedService:'';selection.barber=bs.some(x=>x.id===seedBarber)?seedBarber!:'';message='Revisa el corte sugerido y el horario disponible. Puedes cambiar cualquiera de ellos.'}
  if(!active)return;setShop(sh);setServices(ss);setBarbers(bs);setPhotos(results[3].data??[]);setFav(!!results[4].data);setConsent(!!results[5].data?.enabled);setRewards(results[6].data??[]);setProgram(results[7].data);setOffers(results[8].data??[]);setOfferId('');setRewardId('');setAccept(false);setNote(message);setError('');wantedSlot.current=seedStart??'';setDay(seedStart&&!Number.isNaN(Date.parse(seedStart))?localDay(new Date(seedStart),sh.timezone):localDay(new Date(),sh.timezone));setCut(selection.cut);setExtras(selection.extras);setBarber(selection.barber);
 }catch(e){if(active)setError((e as Error).message)}})();return()=>{active=false}},[id,repeat,seedService,seedBarber,seedStart,session?.user.id]);
 useEffect(()=>{let active=true;setSlot('');setSlots([]);if(!cut||!barber){setSlotBusy(false);return}setSlotBusy(true);rpc<{starts_at:string;ends_at:string}[]>('available_slots',{p_barber:barber,p_day:day,p_service:cut,p_addons:extras}).then(r=>{if(active){setSlots(r);const wanted=wantedSlot.current;wantedSlot.current='';if(wanted){const match=r.find(t=>Date.parse(t.starts_at)===Date.parse(wanted));if(match)setSlot(match.starts_at);else setNote('Ese horario ya no está disponible. Elige otro de la lista.')}setError('')}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setSlotBusy(false)});return()=>{active=false}},[cut,barber,day,extras]);
 const current=services.find(s=>s.id===cut);const q=current&&shop?quote(current,services.filter(s=>extras.includes(s.id)),shop.deposit_percent):null;const reward=rewards.find(r=>r.id===rewardId);const eligibleOffers=offers.filter(o=>o.service_id===cut&&Date.parse(o.ends_at)>now&&(!slot||Date.parse(o.ends_at)>=Date.parse(slot)));const offer=eligibleOffers.find(o=>o.id===offerId);const discount=q&&reward?Math.min(q.total,reward.discount_cents):offer&&current?offerDiscount(offer,current.price_cents):0;const total=q?q.total-discount:0;const deposit=shop?Math.round(total*shop.deposit_percent/100):0;
 useEffect(()=>{setAccept(false);requestId.current=Crypto.randomUUID()},[total,deposit,slot,barber,cut,offerId,rewardId]);
 async function toggleFav(){try{const r=fav?await db().from('favorites').delete().eq('shop_id',id).eq('customer_id',session!.user.id):await db().from('favorites').insert({shop_id:id,customer_id:session!.user.id});if(r.error)throw r.error;setFav(!fav)}catch(e){report(e)}}
 async function marketing(){try{const {error}=await db().from('marketing_consents').upsert({shop_id:id,customer_id:session!.user.id,enabled:!consent,updated_at:new Date().toISOString()});if(error)throw error;setConsent(!consent)}catch(e){report(e)}}
 async function book(){if(!profile){router.push('/login');return}if(!q||!shop||!slot)return;setBusy(true);try{const args={p_barber:barber,p_service:cut,p_addons:extras,p_start:slot,p_expected_total:q.total,p_expected_deposit:shop.deposit_percent,p_expected_cancel:shop.cancel_hours,p_accept:accept};if(paidMode){const r=await db().functions.invoke('create-checkout',{body:{...args,p_request:requestId.current,p_offer:offer?.id??null,p_reward:reward?.id??null,p_expected_discount:discount}});if(r.data?.error)throw Error(r.data.error);if(r.error)throw r.error;if(r.data.url)await Linking.openURL(r.data.url);router.replace('/appointments');return}await rpc(reward?'book_with_reward':offer?'book_with_offer':'book_appointment',reward?{...args,p_reward:reward.id,p_expected_discount:discount}:offer?{...args,p_offer:offer.id,p_expected_discount:discount}:args);let reminderNote='';try{await syncReminders(session!.user.id)}catch{reminderNote=' No pudimos actualizar los recordatorios; revisa Mis citas.'}Alert.alert('Cita de prueba reservada','No se realizó ningún cobro.'+reminderNote);router.replace('/appointments')}catch(e){report(e)}finally{setBusy(false)}}

 function continueBooking(){setTab('services');if(!cut||!barber||!slot){setSection(!cut?'cut':!barber?'barber':'date');requestAnimationFrame(()=>scroll.current?.scrollTo({y:bookingY.current,animated:true}));return}setReviewOpen(true)}
 return <><Screen scrollRef={scroll} footer={shop&&<View style={{gap:10}}><View style={[s.row,{justifyContent:'space-between'}]}><View><Text style={s.heading}>{q?money(total):'Elige tu corte'}</Text><Text style={s.muted}>{q?'Anticipo '+money(deposit)+' · '+q.minutes+' min':'Precios definidos por la barbería'}</Text></View><View style={{minWidth:145}}><Button title={!slot?'Continuar':'Revisar reserva'} disabled={busy||slotBusy||!services.some(v=>v.kind==='cut')||!barbers.length} onPress={continueBooking}/></View></View></View>}><Failure message={error}/>{shop&&<>
 {photos.find(p=>p.kind==='shop')&&<Image source={{uri:photoURL(photos.find(p=>p.kind==='shop')!.storage_path)}} style={{width:'100%',height:195,borderRadius:24}}/>}
 <View style={{gap:8}}><Title>{shop.name}</Title><Verified shop={shop.id}/><Copy>{shop.address} · {shop.municipality}</Copy><Copy>{shop.days.map(d=>['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'][d]).join(', ')} · {shop.open_hour}:00–{shop.close_hour}:00</Copy></View>
 <View style={s.row}><View style={{flex:1}}><Button secondary title={fav?'♥ Favorita':'♡ Guardar'} onPress={toggleFav}/></View><View style={{flex:1}}><Directions shopId={shop.id}/></View></View>
 {!!shop.description&&<Copy>{shop.description}</Copy>}{!!note&&<Card><Copy>{note}</Copy></Card>}
 <ShopTabs value={tab} onChange={setTab}/>
 <ShopSectionContent tab={tab} shop={shop.id} photos={photos} barbers={barbers} onSelectBarber={id=>{wantedSlot.current='';setBarber(id);setTab('services');setSection('date')}}/>
 {tab==='services'&&<View onLayout={e=>{bookingY.current=e.nativeEvent.layout.y}} style={{gap:14}}>
  <BookingSection step="01" title="Elige tu corte" summary={current?`${current.name} · ${money(current.price_cents)}`:"Selecciona un tipo de corte"} open={section==='cut'} onToggle={()=>toggleSection('cut')}>{services.filter(x=>x.kind==='cut').map(service=>{const photo=photos.find(p=>p.service_id===service.id);return <View key={service.id} style={{gap:10,paddingBottom:14,borderBottomWidth:1,borderBottomColor:colors.line}}>{photo&&<Image style={s.photo} source={{uri:photoURL(photo.storage_path)}}/>}<Choice label={`${service.name} · ${money(service.price_cents)} · ${service.duration_minutes} min`} selected={cut===service.id} onPress={()=>{wantedSlot.current='';setCut(service.id);setOfferId('');setExtras([]);setAccept(false);setSection(null)}}/><Copy>{service.description}</Copy></View>})}{!services.some(x=>x.kind==='cut')&&<Copy>La barbería aún no ha publicado sus cortes.</Copy>}
 </BookingSection>
 <BookingSection step="02" title="Dale un extra" summary={extras.length?services.filter(x=>extras.includes(x.id)).map(x=>x.name).join(', ')+' · +'+money(services.filter(x=>extras.includes(x.id)).reduce((sum,x)=>sum+x.price_cents,0)):'Sin extras · opcional'} open={section==='extras'} onToggle={()=>toggleSection('extras')}>{services.filter(x=>x.kind==='addon').map(a=><Choice key={a.id} label={`${a.name} +${money(a.price_cents)} · +${a.duration_minutes} min`} selected={extras.includes(a.id)} onPress={()=>{wantedSlot.current='';setExtras(x=>x.includes(a.id)?x.filter(i=>i!==a.id):[...x,a.id]);setAccept(false)}}/>)}
 <Copy>{services.some(x=>x.kind==='addon')?'Puedes elegir varios extras.':'Esta barbería aún no ofrece extras.'}</Copy>{extras.length>0&&<Button secondary title="Quitar todos los extras" onPress={()=>{wantedSlot.current='';setExtras([]);setAccept(false)}}/>}<Button secondary title="Listo" onPress={()=>setSection(null)}/></BookingSection>
 <BookingSection step="03" title="Elige tu barbero" summary={barbers.find(b=>b.id===barber)?.name??'Selecciona un barbero disponible'} open={section==='barber'} onToggle={()=>toggleSection('barber')}>{barbers.map(b=>{const photo=photos.find(p=>p.barber_id===b.id);return <View key={b.id} style={{gap:10,paddingBottom:10}}>{photo&&<Image source={{uri:photoURL(photo.storage_path)}} style={{height:90,width:90,borderRadius:45}}/>}<Choice label={b.name+' · '+b.specialty} selected={barber===b.id} onPress={()=>{wantedSlot.current='';setBarber(b.id);setSection(null)}}/></View>})}
 {!barbers.length&&<Copy>No hay barberos disponibles por ahora.</Copy>}</BookingSection>
 <BookingSection step="04" title="Fecha y hora" summary={slot?new Date(slot).toLocaleString('es-MX',{timeZone:shop.timezone,day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):day+' · Elige un horario'} open={section==='date'} onToggle={()=>toggleSection('date')}><ScrollView horizontal contentContainerStyle={{gap:8}}>{Array.from({length:14},(_,i)=>{const d=nextDay(localDay(new Date(),shop.timezone),i);return <Choice key={d} label={i===0?'Hoy':i===1?'Mañana':d.slice(5)} selected={day===d} onPress={()=>{wantedSlot.current='';setDay(d);setOfferId('');setAccept(false)}}/>})}</ScrollView><Copy>Horario de {shop.timezone}. La duración incluye tus agregados.</Copy><View style={s.row}>{slots.map(t=><Choice key={t.starts_at} label={new Date(t.starts_at).toLocaleTimeString('es-MX',{timeZone:shop.timezone,hour:'2-digit',minute:'2-digit'})} selected={slot===t.starts_at} onPress={()=>{setSlot(t.starts_at);setAccept(false);setSection(null)}}/>)}</View>{!slots.length&&<><Copy>{slotBusy?'Buscando horarios…':'No hay horarios disponibles con esta selección.'}</Copy>{!slotBusy&&<Button secondary title="Probar el siguiente día" disabled={day>=nextDay(localDay(new Date(),shop.timezone),13)} onPress={()=>{wantedSlot.current='';setDay(nextDay(day,1));setOfferId('');setAccept(false)}}/>}</>}
 {!slotBusy&&!slots.length&&!!cut&&!!barber&&<><Copy>La lista de espera busca espacio para el corte sin agregados. Te avisamos aquí cuando una cancelación o cambio libere un horario.</Copy><Button secondary title="Avisarme si se libera un horario" disabled={busy} onPress={async()=>{setBusy(true);try{await rpc('join_waitlist',{p_barber:barber,p_service:cut,p_day:day});Alert.alert('Estás en la lista','Consulta Avisos y lista de espera para ver los horarios que se liberen.')}catch(e){report(e)}finally{setBusy(false)}}}/><Button secondary title="Ver mis avisos" onPress={()=>router.push('/waitlist')}/></>}</BookingSection>
 {program?.enabled&&<Copy>Cada {program.visits_required} visitas completadas: {money(program.discount_cents)} de recompensa.</Copy>}
 <Choice label="Recibir promociones después de mi visita" selected={consent} onPress={marketing}/><Copy>Puedes retirar este permiso cuando quieras.</Copy></View>}
 <Button secondary title="Reportar barbería" onPress={()=>router.push({pathname:'/support',params:{kind:'shop',target:shop.id}})}/>
 </>}</Screen><Modal visible={reviewOpen} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>{if(!busy)setReviewOpen(false)}}><Screen><Title>Revisa y confirma</Title><Copy>Comprueba el servicio, el barbero y el anticipo antes de reservar.</Copy><Button secondary title="Volver a mi selección" disabled={busy} onPress={()=>setReviewOpen(false)}/>{shop&&<>{q&&<Card><Text style={s.heading}>Tu reserva</Text><Copy>{current?.name} · {barbers.find(b=>b.id===barber)?.name??'Elige barbero'}{'\n'}{slot?new Date(slot).toLocaleString('es-MX',{timeZone:shop.timezone}):'Falta elegir fecha y hora'}</Copy>{!slot&&<Button secondary title="Elegir fecha y hora" onPress={()=>setSection('date')}/>}{eligibleOffers.length>0&&<><Copy>Promociones para este corte. El descuento se aplica al elegirlo; no se combina con recompensas.</Copy><Choice label="Sin promoción" selected={!offer} onPress={()=>{setOfferId('');setAccept(false)}}/>{eligibleOffers.map(o=><View key={o.id} style={{gap:6}}><Choice label={o.title+' · −'+money(offerDiscount(o,current!.price_cents))} selected={offerId===o.id} onPress={()=>{setOfferId(o.id);setRewardId('');setAccept(false)}}/><Copy>{o.conditions} Vigente para citas hasta {new Date(o.ends_at).toLocaleString('es-MX',{timeZone:shop.timezone})}.</Copy></View>)}</>}{rewards.length>0&&<><Copy>Tienes recompensas en esta barbería. Elige una para esta reserva.</Copy><Choice label="Guardar mis recompensas para después" selected={!rewardId} onPress={()=>{setRewardId('');setAccept(false)}}/>{rewards.map(r=><Choice key={r.id} label={'Usar '+money(r.discount_cents)+' de recompensa'} selected={rewardId===r.id} onPress={()=>{setRewardId(r.id);setOfferId('');setAccept(false)}}/>)}</>}<Copy>Precio de catálogo: {money(q.total)}</Copy>{discount>0&&<Copy>{offer?.title??'Recompensa aplicada'}: −{money(discount)}</Copy>}<Text style={s.heading}>Total {money(total)}</Text><Copy>{q.minutes} minutos · Anticipo {money(deposit)} ({shop.deposit_percent}%) · Restante {money(total-deposit)}</Copy><Copy>Cancelación sin penalización hasta {shop.cancel_hours} horas antes. Después, o si no asistes, pierdes el anticipo. Si cancela la barbería, devolución completa.</Copy>{reward&&<Copy>Una recompensa por reserva, sin saldo sobrante. Se devuelve si la cita se cancela; se consume al completar la visita o registrar inasistencia.</Copy>}<Choice label={paidMode?'Acepto las condiciones del anticipo y la cancelación.':'Acepto las condiciones. Esta es una reserva de prueba sin cobro.'} selected={accept} onPress={()=>setAccept(!accept)}/><Button title={busy?'Reservando…':paidMode?'Pagar anticipo y reservar':'Reservar con anticipo de prueba'} disabled={busy||slotBusy||!slot||!accept||!barber} onPress={book}/></Card>}
</>}</Screen></Modal></>
}
